### ISSUE TITLE
README.MD for users

### ISSUE THREAD

**Issue by bcbc** [hakuna-m/wubiuefi#1]
It'd be nice to have a README.MD for users (different from the README on how to compile which is developer-oriented). One that explains how to install (similar to https://www.dropbox.com/sh/6uqomp8l1frcd1y/AAAaXxnSv_-YeA9Gfx5D19nka/readme.txt?dl=0)

Then I can edit the Askubuntu Wubi 'tag' and add a link to github as the new site for Wubi https://askubuntu.com/tags/wubi/info

**Comment by hakuna-m** [comment]
I created a [Wiki site](https://github.com/hakuna-m/wubiuefi/wiki) in Markdown. It is still under construction but IMHO it serves the purpose instead of a README.md.

**Comment by bcbc** [comment]
Better idea.
I updated the Wubi tag info on askubuntu.com and added a link to the Wiki as well as the latest release. 

Note: the changes won't show up until they have been peer-reviewed (and survive being peer-reviewed :)
