### ISSUE TITLE
wubi1604r309

### ISSUE THREAD

**Issue by ericspakauskie** [hakuna-m/wubiuefi#10]
Kubuntu is not working. it only shows the glowing Kubuntu icon then computer restarts again.

**Comment by hakuna-m** [comment]
After the first restart it should display: 
```
Completing the Ubuntu installation.
For more installation boot options, press `ESC' now...
```
There you can press `ESC` and then you can select "Verbose mode" in the following menu:
```
Normal mode
Safe graphic mode
ACPI workarounds
Verbose mode
Demo mode 
```
In "verbose mode" it collects more information for debugging but it is also a workaround for some issues. In some tests, it worked in "verbose mode", if default mode "normal mode" didn't work.

Note: Kubuntu only shows a background picture and a mouse cursor during second part of installation.  That doesn't mean that it doesn't work.

**Comment by ericspakauskie** [comment]
Yes it is working now. Thanks!
