### ISSUE TITLE
Permission Denied While Installing Ubuntu Through Wubi

### ISSUE THREAD

**Issue by TheOfficialGameDev** [hakuna-m/wubiuefi#105]
I have download the Ubuntu.iso file and moved to the same location of wubi.exe it seems to first install correctly bet after it is done installing it says Permission Denied so if anyone how how to fix this please tell me.  thank you for all advice given

**Comment by bunnyden** [comment]
my pc actually does not have UEFI support

**Comment by hakuna-m** [comment]
But "permission denied" errors are not typical UEFI errors and Wubiuefi supports systems with UEFI and without UEFI, too.

The log file should also contain the detected BIOS mode:

`DEBUG  WindowsBackend: EFI boot = False `

means Legacy BIOS (=non UEFI)

`DEBUG  WindowsBackend: EFI boot = True`

means UEFI

But as I wrote above, your "permission denied" error is not a typical UEFI error. So the error messages in the log are more important than UEFI information.

**Comment by bunnyden** [comment]
My motherboard does not give me the choice of UEFI and my motherboard is 2007 model

**Comment by bunnyden** [comment]
But planning on upgrading

**Comment by bunnyden** [comment]
and this is my error log [https://docs.google.com/document/d/12EjVyx15gdLSDTrDqBIeR3oYICd7D9tugtCzkMcFNG0/edit?usp=sharing](url)

**Comment by bunnyden** [comment]
[https://docs.google.com/document/d/12EjVyx15gdLSDTrDqBIeR3oYICd7D9tugtCzkMcFNG0/edit?usp=sharing](url)

**Comment by bunnyden** [comment]
my error log https://docs.google.com/document/d/12EjVyx15gdLSDTrDqBIeR3oYICd7D9tugtCzkMcFNG0/edit?usp=sharing

**Comment by hakuna-m** [comment]
> ```
> 05-30 07:52 ERROR  TaskList: [Errno 13] Permission denied: 'C:\\wubildr'
> Traceback (most recent call last):
>   File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
>   File "\lib\wubi\backends\win32\backend.py", line 791, in modify_bcd
>   File "\lib\shutil.py", line 83, in copyfile
> IOError: [Errno 13] Permission denied: 'C:\\wubildr'
> ```
The error does not depend on UEFI. Wubi(uefi) tries to copy the file **wubildr** to the root directory of the Windows system drive C:

**wubildr** is part of the non UEFI boot loader. If you select "Ubuntu", Windows bootloader runs **wubildr.mbr** and **wubildr.mbr** runs **wubildr**.  The search paths of **wubildr.mbr** are only root directories. So Wubi(uefi) copies **wubildr** to the first root directory of your system.

So your current Windows user profile seems to have no permission for root directory of C:. So try to run Wubi(uefi) as administrator. Be sure that no antivirus program denies access.
