### ISSUE TITLE
Installing without downloading

### ISSUE THREAD

**Issue by van9petryk** [hakuna-m/wubiuefi#110]
It will be good feature: install linux distro without downloading it, simply selecting path to distro that I just have downloaded.

**Comment by hakuna-m** [comment]
Do you mean something like ["How can I use a pre-downloaded ISO file ?"](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-use-a-pre-downloaded-iso-file-) ?

**Comment by van9petryk** [comment]
Yes. Thank you.
