### ISSUE TITLE
Wubi 18.04.1 not see xubuntu-18.04.1-desktop-amd64.iso

### ISSUE THREAD

**Issue by nikitastepan0v** [hakuna-m/wubiuefi#115]
Wubi 18.04.1 not see xubuntu-18.04.1-desktop-amd64.iso

**Comment by nikitastepan0v** [comment]
[wubi-18.04.1-rev332.log](https://github.com/hakuna-m/wubiuefi/files/2332830/wubi-18.04.1-rev332.log)

**Comment by hakuna-m** [comment]
> ```
> 08-29 21:50 DEBUG  Distro:   checking Xubuntu ISO E:\Downloads\xubuntu-18.04.1-desktop-amd64.iso
> 08-29 21:50 DEBUG  Distro:     does not contain casper\initrd.lz
> ```
xubuntu-18.04.1-desktop-amd64.iso uses **casper\initrd**, 
xubuntu-18.04.1-desktop-i386.iso uses **casper\initrd.lz** and
ubuntu-18.04.1-desktop-amd64.iso uses **casper\initrd.lz**

There is a mixture of **casper\initrd.lz** and **casper\initrd** for 18.04.1. So we need the changes of rev. 333 with a new isolist.ini for 18.04.1

It is like #112 for 16.04.5 but 16.04.5 only uses **casper\initrd**.

**Comment by hakuna-m** [comment]
It is really a liittle bit confusing but IMHO we need **initrd.lz** for 

- Ubuntu amd64
- Xubuntu i386
- Lubuntu amd64
- Ubuntu Studio i386+amd64
- Ubuntu Kylin amd64

But we need **initrd** for 

- Kubuntu i386+amd64
- Xubuntu amd64
- Ubuntu Budgie i386+amd64
- Lubuntu i386
- Ubuntu MATE i386+amd64
- Ubuntu Kylin i386

**initrd.lz** works with rev.**332** but **initrd** needs rev.**333**

So I created a new branch for [Ubuntu 18.04 Bionic Beaver](https://github.com/hakuna-m/wubiuefi/tree/bionic) and changed data/isolist.ini to support initrd or initrd.lz for different 18.04.1 distros.

**Comment by hakuna-m** [comment]
As the issues has not been reported for [18041r333](https://github.com/hakuna-m/wubiuefi/releases/tag/18041r333) since I released it, IMHO we can close the issue.
