### ISSUE TITLE
boot into grub instead ubuntu 18.04.1

### ISSUE THREAD

**Issue by TonyStark** [hakuna-m/wubiuefi#119]
i installed ubuntu 18.04.1 with latest release of wubi alongwith windows10
after reboot it open verification failed windows so i enroll key as per guide
then reboot again and it boot to grub
i also enter boot command and it said that load kernel first
any solution please?

**Comment by hakuna-m** [comment]
> any solution please?

There are often solutions depending on your computer model and configuration. So please add more information about your system.

**Comment by TonyStark** [comment]
My laptop is
Dell 3567
Win 10
i3 6th gen

**Comment by TonyStark** [comment]
also i tried this wubi from this comment (https://github.com/hakuna-m/wubiuefi/issues/102#issuecomment-389173054)
but same problem appear (vmlinuz not found) as per that comment
i choose penguin icon option too, then it appear grub window only

**Comment by hakuna-m** [comment]
> also i tried this wubi from this comment ([#102 (comment)](https://github.com/hakuna-m/wubiuefi/issues/102#issuecomment-389173054))
If your Dell has the same issue, it is necessary to change SATA Operation from RAID-On to AHCI. see [http://triplescomputers.com/blog/uncategorized/solution-switch-windows-10-from-raidide-to-ahci-operation]. 

Unfortunately, some RAID modes are not supported by Linux drivers. If you use Wubi(uefi) to install Ubuntu, the Wubi(uefi) setup works with Windows drivers, but Ubuntu still needs Linux drivers.

**Comment by TonyStark** [comment]
Does this setting cause any future problem? I mean my hard disk is not sata, so will that work? Or what if i make a 80gb partition and install ubuntu on that partition using live usb

**Comment by TonyStark** [comment]
I follow your suggested link, and i found that my sata operation is already switched to AHCI.
There is no raid option there. Only two option available in my sata operation that disable and ahci only

**Comment by TonyStark** [comment]
Magic, somehow now no grub windows coming. Installing ubuntu..

**Comment by hakuna-m** [comment]
> Does this setting cause any future problem?

There is no warranty that there are no problems, especially on Windows. As you see [here](http://triplescomputers.com/blog/uncategorized/solution-switch-windows-10-from-raidide-to-ahci-operation) there are also warnings. 

> Or what if i make a 80gb partition and install ubuntu on that partition using live usb

The main question is whether live usb can see your partition. Live usb also uses Linux drivers.

> Magic, somehow now no grub windows coming.

Maybe, you connected/disconnected a live usb or a drive if you did not change a BIOS setting.

> then suddenly everything is removing like thunderbird, samba, libreoffice, some libraries etc

Really everything ? First, it installs a set of packages, then it removes unused packages for unselected languages or packages which are only used during installation. So removing of some packages is intended. e.g. there are a lot of language packages for thunderbird or libreoffice:

```
thunderbird-locale-de	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-en	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-en-gb	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-en-us	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-es	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-es-ar	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-es-es	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-fr	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-it	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-pt	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-pt-br	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-pt-pt	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-ru	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-zh-cn	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-zh-hans	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-zh-hant	1:52.9.1+build3-0ubuntu0.18.04.1
thunderbird-locale-zh-tw	1:52.9.1+build3-0ubuntu0.18.04.1
libreoffice-help-de	1:6.0.3-0ubuntu1
libreoffice-help-en-gb	1:6.0.3-0ubuntu1
libreoffice-help-en-us	1:6.0.3-0ubuntu1
libreoffice-help-es	1:6.0.3-0ubuntu1
libreoffice-help-fr	1:6.0.3-0ubuntu1
libreoffice-help-it	1:6.0.3-0ubuntu1
libreoffice-help-pt	1:6.0.3-0ubuntu1
libreoffice-help-pt-br	1:6.0.3-0ubuntu1
libreoffice-help-ru	1:6.0.3-0ubuntu1
libreoffice-help-zh-cn	1:6.0.3-0ubuntu1
libreoffice-help-zh-tw	1:6.0.3-0ubuntu1
libreoffice-l10n-de	1:6.0.3-0ubuntu1
libreoffice-l10n-en-gb	1:6.0.3-0ubuntu1
libreoffice-l10n-en-za	1:6.0.3-0ubuntu1
libreoffice-l10n-es	1:6.0.3-0ubuntu1
libreoffice-l10n-fr	1:6.0.3-0ubuntu1
libreoffice-l10n-it	1:6.0.3-0ubuntu1
libreoffice-l10n-pt	1:6.0.3-0ubuntu1
libreoffice-l10n-pt-br	1:6.0.3-0ubuntu1
libreoffice-l10n-ru	1:6.0.3-0ubuntu1
libreoffice-l10n-zh-cn	1:6.0.3-0ubuntu1
libreoffice-l10n-zh-tw	1:6.0.3-0ubuntu1
```

**Comment by TonyStark** [comment]
Yes it removes all installed packages, i installed ubuntu 2 times, after installing grub2 it start removing all package process

**Comment by TonyStark** [comment]
Yes it removes all installed packages, i installed ubuntu 2 times, after installing grub2 it start removing all package process

**Comment by TonyStark** [comment]
I did not install from live usb,because I'm new in partition things. 
Currently i unistalled wubi (ubuntu 18.04.1)but still "ubuntu" shows in boot manager.

Right now i downloaded 16.04.5 ubuntu and trying to installing using wubi16045 version
After wubi setup successful i reboot laptop and it auto boot to ubuntu 16.04.5 installation.
Now i saw that same installation things happening. (Eg. Copying files, installing system,install grub package.... Then it start removing/completely removing packages process....)
After all process done it reboot, and i enter boot manager (by pressing F12)
It shows ubuntu and windows boot manager options
I choose ubuntu and it open grub (version 2.0.2~beta2-36ubuntu3.18)
I guess ubuntu16.04.5 have beta grub version

So it still not works on another ubuntu version... 😟😟😟

**Comment by TonyStark** [comment]
I uninstalled ubuntu16.04.5 wubi from windows control panel, and reboot. But still it shows ubuntu in boot manager and it open that beta grub version....lol
How is that possible?

**Comment by hakuna-m** [comment]
> How is that possible?

see [Wubiuefi logs](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-are-the-logs-for-wubiuefi-)

look for line
`INFO   CommonBackend: This is the uninstaller running`
and the lines below

**Comment by TonyStark** [comment]
[wubi-16.04.5-rev333.log](https://github.com/hakuna-m/wubiuefi/files/2497780/wubi-16.04.5-rev333.log)
[wubi-18.04.1-rev333.log](https://github.com/hakuna-m/wubiuefi/files/2497781/wubi-18.04.1-rev333.log)
[wubi-18.04-rev331.0.log](https://github.com/hakuna-m/wubiuefi/files/2497782/wubi-18.04-rev331.0.log)
okay
here i uploaded wubi log
however i installed linux mint alongwith windows 10
anyway im closing this issue.
thank you for your support :)
