### ISSUE TITLE
Mounting swap as none fails on Wubi for Ubuntu 18.04.1 (rev 333)

### ISSUE THREAD

**Issue by mreymann** [hakuna-m/wubiuefi#125]
Hello,

Upon reboot the Ubuntu installer complains that the swap file /host/ubuntu/disks/swap.disk cannot be mounted "none" (or something along these lines, the message is in German).
When I hit "Continue", the installer just hangs and details show repeating errors about "expected snap revision xxxx to be mounted ... but it is not".

I've also tried older Wubi revisions and the 18.10 version. They all show the same symptom.
Is there a fix for this?

Regards

**Comment by hakuna-m** [comment]
> Upon reboot the Ubuntu installer complains that the **swap** file /host/ubuntu/disks/swap.disk cannot be mounted "none" (or something along these lines, the message is in German).
> When I hit "Continue", the installer just hangs and details show repeating errors about "expected **snap** revision xxxx to be mounted ... but it is not".

**swap** and **snap** are similar words with a different meaning. Compare [swap](https://help.ubuntu.com/community/SwapFaq) and [snap](https://docs.snapcraft.io/snap-documentation/3781). 

So it is not necessary that both messages have the same reason.

Can you report exact error messages ? If you get only German messages, it is also no problem. 
Which ISO did you use for your tries ? The same ISO or different ISOs downloaded by different versions of Wubiuefi ?

**Comment by hakuna-m** [comment]
The corresponding English error messages....

> Do you want to resume partitioning?
> 
> The attempt to mount a file system with type **swap** in **/host/ubuntu/disks/swap.disk** at
> **none** failed.
>  
> You may resume partitioning from the partitioning menu.

... indicate an issue with the Windows file system or partition of your system. The selected Windows drive for installation (e.g. C: on Windows) should be mounted on **/host** with write access.

Probably, the used Windows file system or partition (Windows drive) is not supported.

Can you boot into "demo mode" (see [here](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-set-boot-options-) ),
list the partition layout in a [terminal](https://help.ubuntu.com/community/UsingTheTerminal) with
`sudo parted --list`
and report the file system disk space usage with
`df -h`

**Comment by mreymann** [comment]
Hello hakuna matata,

Sorry for the late reply & Happy New Year!

Here is the requested output:

![img_20190107_095000](https://user-images.githubusercontent.com/31735558/50758791-7e355f00-1263-11e9-8248-22f618a6c0ab.jpg)

**Comment by mreymann** [comment]
Ideas anyone? I really want my Wubi back! :-)

**Comment by hakuna-m** [comment]
Sorry for my late reply.
> I really want my Wubi back! :-)
Does this mean that an old Wubi version still exists ? If there are more than one Wubi,  there are somtimes issues to detect the right Wubi. 

In your case, the new Wubi should be on /dev/sdb2 which is mounted as /isodevice. Probably the iso file on /ubuntu/install/installation.iso exists only on /dev/sdb2 but maybe /ubuntu/disks/root.disk or /ubuntu/disks/swap.disk exist on /dev/sda3, too?

So, if a second install exists rename the folder of the old install from ubuntu to ubuntuold or something else. Additionally, the installation needs empty disk files. The installation fails if the disk files are not empty.

**Comment by mreymann** [comment]
No, unfortunately, my old Wubi installation doesn't exist anymore (no more C:\ubuntu folder). After I let CCCleaner "clean" my Windows registry, Wubi didn't boot anymore.  So I uninstalled it and tried to reinstall, but it failed with the symptoms described above. What can I do?

**Comment by mreymann** [comment]
SUCCESS!!! I've found a workaround! I took my second SSD drive offline in the "Windows-Datenträgerverwaltung" (Windows drive management?). After that I was able to install Wubi!

Before:

![2019-02-06 10_07_29-window](https://user-images.githubusercontent.com/31735558/52331514-acd85e00-29f8-11e9-8980-9794bfeb5b2f.png)

After:

![2019-02-06 10_07_08-window](https://user-images.githubusercontent.com/31735558/52331542-c083c480-29f8-11e9-8a70-1f39eabd5795.png)

After Wubu is installed, I took the SSD online again. Up to now, everything works as expected! :-)

**Comment by hakuna-m** [comment]
> SUCCESS!!!

That is good news.

The "Windows Disk Management" shows that disk # 0 is a [Dynamic Disk](https://docs.microsoft.com/en-us/windows/desktop/fileio/basic-and-dynamic-disks#dynamic-disks) which is not supported by Wubi and also Ubuntu support without Wubi is tricky ( see [ldmtool](http://manpages.ubuntu.com/manpages/bionic/man1/ldmtool.1.html) )

So there is also an explanation why your solution worked.

**Comment by mreymann** [comment]
Thanks for your support! Wubi is great! :-)
