### ISSUE TITLE
Error installing ubuntu 16.04 wubi16.04r310 with windows 10 64-bit release 14366

### ISSUE THREAD

**Issue by ilianiron** [hakuna-m/wubiuefi#13]
Hello dear Hakuna, it's a new issue-i had a dual boot windows 10/ubuntu configuration installed via wubi16.04r309 .But when installed latest windows release 14366 in slow channel, after restarting to go in to ubuntu give me this error:
https://goo.gl/photos/R3agVVUfVuh6ekgu5
 I will try reinstalling twice with wubi 16.04310 and 310-2 but gave this error again!New windows release broke alongside ubuntu installation, and after that couldn't install again!

**Comment by hakuna-m** [comment]
IMHO 0xc000000e means that a required device is inaccessible.

Maybe, an external disk is connected or your Windows file system has errors. Can you unplug all external disks and can you check your Windows file system ?

Additionally, can you append your log file which you find in Windows temp folder (%temp%) ?

**Comment by hakuna-m** [comment]
Neosmart (program EasyBCD) has an overview of possible causes of 0xc000000e errors: see [Neosmart Wiki]( https://neosmart.net/wiki/0xc000000e)

Maybe, it is also a BCD issue. Is your Windows 10 really not installed in UEFI mode ?  Booting with wubildr.mbr doesn't work in UEFI mode but Wubi tries to detect UEFI mode with

`bcdedit /enum`

If it finds **bootmgfw.efi** or **winload.efi** it creates a BCD entry for UEFI mode.

**Comment by ilianiron** [comment]
Previous version of windows work well with wubi, no problems with
installation, but latest build 14366 that installs 10 days ago broke ubuntu
instalation and i will try with wubi 310 2 times but unsuccesful!

2016-06-25 10:27 GMT+03:00 hakuna matata <notifications@github.com>:

**Comment by ilianiron** [comment]
Here is my log file after installation

2016-06-25 16:01 GMT+03:00 Ilian Zhelyazov <ilianiron@gmail.com>:

**Comment by hakuna-m** [comment]
> Previous version of windows work well with wubi, no problems with installation, but latest build 14366 that installs 10 days ago broke ubuntu instalation

If it works with a previous Windows 10 build, it is a Microsoft bug. I hope that Microsoft will fix the bug soon without needing a bug report of us. IMHO the bug should affect also a lot of people without Wubi, too. 

> Here is my log file after installation

I haven't received your log file. But it doesn't matter. As I wrote, Microsoft should fix the bug.

**Comment by hakuna-m** [comment]
Nevertheless, if Microsoft doesn't fix it, because it says, "it is a new feature and not a bug", there are other possibilities. 

As far as I know, the bug affects only an install in legacy BIOS mode. Is it an option for you to install your Windows 10 in UEFI mode ?

Is it possible to fix it with [EasyBCD](http://neosmart.net/EasyBCD) ? It should be possible to edit the Ubuntu menu entry in legacy BIOS mode. There are only [limitations in UEFI mode](https://neosmart.net/wiki/easybcd/uefi).

**Comment by ilianiron** [comment]
Hello dear Hakuna, i have yesterday install EASYBCD and it,s work!!!Ubuntu
install with wubi 1604r310 with no problem!Thank's a lot dear friend!!

2016-06-26 0:00 GMT+03:00 hakuna matata <notifications@github.com>:

**Comment by astrung** [comment]
@hakuna-m @ilianiron how can you fix that ? i have same problem. I bought an external driver to install ubuntu on it with wubi. I formatted it to basic disk in window, then i installed ubuntu by wubi. 

My computer has Windows 10 - legacy BIOS - no secured boot. Then ubuntu option has  been appeared, but when i selected it, my screen shows error : `\ubuntu\winboot\wubildr.mbr` - `0xc000000e`. But i have edited it by bcdedit to right path On my local computer, it is in new disk : F:\\ubuntu\winboot\wubildr.mbr . So i config it :
