### ISSUE TITLE
Not an issue, but a question. Edit: Actually a few questions.

### ISSUE THREAD

**Issue by Aresiel** [hakuna-m/wubiuefi#132]
If I use Wubirelease 18042r333, will I be able too follow this guide https://wiki.ubuntu.com/WubiGuide for installing it? And after following that guide, will I be able too reboot and use Linux or will I need to screw around with more things? I'm just asking this because I would rather not accidentally break anything on my computer. Also will I need to partition my harddrive for it? And if not, can I access the Ubuntu file system in Windows and vice versa? I also saw something about secure boot, is it done automatically or do I have to screw around with it too make it work? And does it work on windows 10?

**Comment by hakuna-m** [comment]
IMHO, a lot of questions are already answered in our [FAQ](https://github.com/hakuna-m/wubiuefi/wiki/FAQ) 

Which questions are still open after reading our [Wiki](https://github.com/hakuna-m/wubiuefi/wiki) and [FAQ](https://github.com/hakuna-m/wubiuefi/wiki/FAQ) ?

**Comment by Aresiel** [comment]
After reading those two, I still wonder if I can somehow access the Ubuntu file system from Windows?

**Comment by hakuna-m** [comment]
Windows does not support Linux file systems by default. But it is possible to install drivers or programs with support for Linux file systems.

For Wubi(uefi) configuration it is only necessary to read **/ubuntu/disks/root.disk** on installation drive. (e.g. C:). Programs like [7-zip](https://www.7-zip.org/) provide support for the used [ext4](https://en.wikipedia.org/wiki/Ext4) file system.

**Comment by Aresiel** [comment]
Ok
