### ISSUE TITLE
Beep on boot

### ISSUE THREAD

**Issue by Aresiel** [hakuna-m/wubiuefi#134]
Computer makes a beeping noise when it boots. Everything is working, running Ubuntu 18.10 alongside Windows 10. Just wondering why it beeps and if I can disable it?

**Comment by Aresiel** [comment]
Just thought you may want some details about my computer, It's running Windows 10 Home 1809 17763.379. I have an Lenovo 36D5 motherboard version SDK0J40700 WIN 3258011873159. Used wubi1810r334.exe for installing it with 32GB size, default accessability options and normal Ubuntu as the OS. It beeps before booting into whichever OS was the last selected in the UEFI menu.

**Comment by hakuna-m** [comment]
> It beeps before booting into whichever OS was the last selected in the UEFI menu.

Beeps before or in the UEFI menu should be part of the BIOS/firmware settings. Wubiuefi has probably disabled skipping of UEFI menu but it does not change settings for beeps. So a possible solution for Lenovo is https://forums.lenovo.com/t5/General-Discussion-Knowledge/How-do-I-turn-off-system-event-beeps/ta-p/328397

**Comment by Aresiel** [comment]
Ok, I'll take a look at it.
