### ISSUE TITLE
Desktop environment 

### ISSUE THREAD

**Issue by iuuukhueeee** [hakuna-m/wubiuefi#145]
I have a problem with wubi version 18.04.2 (rev 333)
I see that the version have supported Ubuntu (64 bit only), Kubuntu (*), Lubuntu, Ubuntu Studio, Ubuntu MATE, Xubuntu, Ubuntu Kylin, Ubuntu Budgie
But when I open, it only has one environment "Ubuntu" 
![Untitled](https://user-images.githubusercontent.com/21292391/56866541-8ed13700-6a04-11e9-9265-be3d849f53ff.png)
Is it a bug??

Thank you!!

**Comment by hakuna-m** [comment]
> Is it a bug??

It is a feature, if there is an existing ISO file. see [How can I use a pre-downloaded ISO file ?](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-use-a-pre-downloaded-iso-file-)

**Comment by hl11jp** [comment]
Thanks for your help!! Much appreciated.

I know this is not kind of question that you want to get but.. Please, could you do for me a favor? I really really want you to support Kali Linux. It's too hard for me to install the Kali Linux. BIOS of my Pc doesn't support usb boot, i guess. Even I try Plop boot manager but it can't be helped..

Thank you!!
