### ISSUE TITLE
Can't install Ubuntu 18.04.2 with Windows 10 Pro

### ISSUE THREAD

**Issue by SaravananAnbu** [hakuna-m/wubiuefi#151]
Am trying to dual boot with D: drive but after run wubiuefi am getting the error
![WhatsApp Image 2019-05-29 at 12 14 53 AM (1)](https://user-images.githubusercontent.com/38387413/58710280-97d56f80-83d9-11e9-8097-f093aa6b3898.jpeg)

Here, there is no path like this.

**Comment by hakuna-m** [comment]
> Here, there is no path like this

The path should be on EFI partition. EFI partition is hidden on Windows and therefore it has no drive letter by default.

If you need a drive letter to check and correct the EFI partition on Windows you can....
- open the command prompt as administrator: e.g. https://www.howtogeek.com/194041/how-to-open-the-command-prompt-as-administrator-in-windows-8.1/

- type e.g.
`mountvol s: /s`
to assign the EFI partition to drive s:

- if necessary copy the files from installation folder **D:\ubuntu\winboot\EFI** to EFI partition folder **S:\EFI\ubuntu\wubildr** e.g.
`copy "D:\ubuntu\winboot\EFI\grubx64.efi" "S:\EFI\ubuntu\wubildr\grubx64.efi"`

BUT Wubiuefi does copy these files by default and it creates a boot menu entry which runs shimx64.efi and not grubx64.efi.

So probably grubx64.efi is the wrong loader if Secure Boot is enabled.

**Comment by SaravananAnbu** [comment]
when I run mountvol s: /s,
It says directory is not empty

**Comment by hakuna-m** [comment]
> when I run mountvol s: /s,
> It says directory is not empty

i.e. drive s: is already in use. 

type
`mountvol`
without parameters to list all options and also possible partitions for dirves.

Depending on the current use of s: , you can 

use another **unused** drive letter for the EFI partition. e.g. t:

`mountvol t: /s`

OR

unmount an used drive letter e.g. s:

`mountvol s: /d` and mount it again with `mountvol s: /s`

OR

see answers of [How to access efi partition on windows 10?](https://superuser.com/questions/965751/how-to-access-efi-partition-on-windows-10)

**Comment by SaravananAnbu** [comment]
Thank You @hakuna-m
