### ISSUE TITLE
IO Error url open [erno 10051]

### ISSUE THREAD

**Issue by Alymostafa** [hakuna-m/wubiuefi#153]
a socket operation was attempted to an unreachable network 
for more info please see the log file :
IN log file :
The process cannot access the file because it is being used by another process: u'C:\\ubuntu\\install\\ubuntu-16.04.6-desktop-amd64.iso'

**Comment by hakuna-m** [comment]
> a socket operation was attempted to an unreachable network

If it is not a general issue of your network or internet connection, you need the tried URL from your log.

The tried URL is in the line above the erno 10051 message. 

> The process cannot access the file because it is being used by another process: u'C:\ubuntu\install\ubuntu-16.04.6-desktop-amd64.iso'

That line logs a resulting issue.

**Comment by Alymostafa** [comment]
so if i solve the problem in logs files the whole problem will be solved ??

**Comment by hakuna-m** [comment]
You need the failed URL to check it. If you add it in your next post, I can also check the URL.

If the URL works on my check, it is a local issue network issue of your computer. If it also doesn't work on my check, I can try to find the reason of the issue.

**Comment by Alymostafa** [comment]
thank you i solved it the error was some process was using this process
