### ISSUE TITLE
Does Wubi support Lubuntu Alternate?

### ISSUE THREAD

**Issue by BassemN** [hakuna-m/wubiuefi#157]
Hello,

I know that Wubi supports Lubuntu but does it also supports [Lubuntu Alternate](https://help.ubuntu.com/community/Lubuntu/Alternate_ISO)?

Many thanks

**Comment by hakuna-m** [comment]
AFAIK, [Lubuntu Alternate](https://help.ubuntu.com/community/Lubuntu/Alternate_ISO) does not use graphical installer [Ubiquity](https://wiki.ubuntu.com/Ubiquity). So it is currently not supported.

**Comment by BassemN** [comment]
Thanks a lot :)
