### ISSUE TITLE
After installing

### ISSUE THREAD

**Issue by ItZskyler** [hakuna-m/wubiuefi#168]
When i installed it it said something about efi or uefi and that the boot may fail, after i go on windows and go back after some time it gives me a black initframs screen, any fix at all?

**Comment by hakuna-m** [comment]
> When i installed it it said something about efi or uefi and that the boot may fail

... is a known issue ( see [release notes -> known issues](https://github.com/hakuna-m/wubiuefi/releases/tag/1904r336)) but IMHO it is not the reason for ....
> it gives me a black initframs screen

There are some possible reasons. e.g hibernation like in #37 

Is there no additional error message ?

**Comment by x-Sunchi** [comment]
Hi, ItZskyler is my account.

It works right now without a problem but thanks for the help!

**Comment by ItZskyler** [comment]
He is,

i'll now close this issue 

Thanks again
