### ISSUE TITLE
Ubuntu Upgrade to 19.10 from 19.04 - stuck at initramfs

### ISSUE THREAD

**Issue by zhhaa** [hakuna-m/wubiuefi#169]
While upgrading to 19.10 from 19.04, the system suddenly hanged at installing the files. I waited for 20 mins but nothing happened, so I force powered off the system. After powering on, as usual the customised grub theme came up, I opted to boot into ubuntu but it took me to initramfs.

In the initramfs '- continue' did nothing, '-exit' ended with a kernel panic. 

Is there any way to fix this with a live image or some other method ? The files inside the disk are not a priority but the customisations I have performed to make the ubuntu to my ease are the ones stopping me from reinstall.

**Comment by hakuna-m** [comment]
> While upgrading to 19.10 from 19.04, the system suddenly hanged at installing the files.

IMHO, it sounds like a general issue for Ubuntu,

Try `reboot ` and choose an older kernel in recovery mode from boot menu. Does that work ?

> The files inside the disk are not a priority but the customisations I have performed to make the ubuntu to my ease are the ones stopping me from reinstall.

Are there backups ?

**Comment by zhhaa** [comment]
There are no backups. Recovery mode option - will try and tell

**Comment by zhhaa** [comment]
> > While upgrading to 19.10 from 19.04, the system suddenly hanged at installing the files.
> 
> IMHO, it sounds like a general issue for Ubuntu,
> 
> Try `reboot ` and choose an older kernel in recovery mode from boot menu. Does that work ?
> 
> > The files inside the disk are not a priority but the customisations I have performed to make the ubuntu to my ease are the ones stopping me from reinstall.
> 
> Are there backups ?

Recovery mode option using kernel 5.0.0-31 also stuck at initramfs.

**Comment by zhhaa** [comment]
I did a sudo fsck on the root.disk from live cd. This fixed the initramfs but now the boot is stuck at "A start job is running for Loads AppArmor profiles ". 

The first "Failed" started at "Failed to start Remount Root and Kernel File systems".
 After fifteen minutes it stopped at pciebus error.


Recovery mode - gave me some options but none worked as r/w mode could not be done.

Is it fixable?

**Comment by ilkersigirci** [comment]
Unfortunately, I got the same error today. Is there any fix?

**Comment by hakuna-m** [comment]
We tested Wubiuefi for Ubuntu 19.10. We noted that the file **/usr/share/initramfs-tools/scripts/local** from package [initramfs-tools-core](https://packages.ubuntu.com/nitramfs-tools-core) has been changed for Ubuntu 19.10.

So existing patch for previous Ubuntu versions does not work and old Ubuntu bug [1317437](https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/1317437) occurs again.

I changed the patch **loop-remount**. So the initramfs issue should be fixed for wubi1910r338 or later.

If you installed Ubuntu with older Wubiuefi versions there is the following workaround to install the new patch: 

Change boot option from `ro` to `rw` within grub boot menu for a temporary workaround without patch: 

- edit boot entry "Ubuntu" by pressing <kbd>e</kbd> 
- go to line 
`linux	/boot/vmlinuz-3.13.0-170-generic root=UUID=1234567890ABCDEF loop=/ubuntu/disks/root.disk ro   quiet splash $vt_handoff`
- change `ro` to `rw`. 
`linux	/boot/vmlinuz-3.13.0-170-generic root=UUID=1234567890ABCDEF loop=/ubuntu/disks/root.disk rw   quiet splash $vt_handoff`
- boot with changed line by pressing <kbd>F10</kbd> 

Then you can install the new patch:

```
sudo wget https://raw.githubusercontent.com/hakuna-m/wubiuefi/master/data/custom-installation/patch/loop-remount -O /etc/initramfs-tools/hooks/loop-remount
sudo chmod +x /etc/initramfs-tools/hooks/loop-remount
sudo update-initramfs -u
```

**Comment by zhhaa** [comment]
My issue is fixed, back to ubuntu now. If it is fixed for @ilkersigirci then you can close this.

**Comment by ilkersigirci** [comment]
My issue is also fixed. Thanks for the quick fix. Please, close the issue.

**Comment by zhhaa** [comment]
.

**Comment by claudio791** [comment]
> 
> 
> We tested Wubiuefi for Ubuntu 19.10. We noted that the file **/usr/share/initramfs-tools/scripts/local** from package [initramfs-tools-core](https://packages.ubuntu.com/nitramfs-tools-core) has been changed for Ubuntu 19.10.
> 
> So the initramfs issue should be fixed for wubi1910r338 or later.

I've been waiting for wubi1910r338.exe since October 17, 2019 when Ubuntu 19.10 was officially released.
I didn't check the whole Wubiuefi story but it seems like there has never been such a large delay.
I'm worried.

**Comment by hakuna-m** [comment]
> I didn't check the whole Wubiuefi story but it seems like there has never been such a large delay.
> I'm worried.

Don't worry. I released the source code for r338 14 days ago. The built exe worked as expected but we want suppress also the EFI warnings from [1904r336](https://github.com/hakuna-m/wubiuefi/releases/tag/1904r336), which seems to be a growing issue e.g. for Kubuntu installer which has no possibility to skip warnings manually.

So we have waited until the EFI warnings are fixed or someone needs a built exe. The EFI warnings are only partly fixed but if you need a built exe (you can also build it from source code), I will release it.
