### ISSUE TITLE
Wubi fails to detect ubuntu-16.04.1-desktop-i386 ISO

### ISSUE THREAD

**Issue by realmatrix** [hakuna-m/wubiuefi#17]
Wubi fails to detect ubuntu-16.04.1-desktop-i386 ISO

08-17 21:24 DEBUG  Distro:     does not contain casper\vmlinuz.efi

only casper\vmlinuz exist

**Comment by hakuna-m** [comment]
Do you try Wubi on a system with a 64 bit CPU ? vmlinuz**.efi** is the default value for 64 bit ISOs.

see [Can I force Wubi to download and install a 32 bit version of Ubuntu?](https://wiki.ubuntu.com/WubiGuide#Can_I_force_Wubi_to_download_and_install_a_32_bit_version_of_Ubuntu.3F)
or [How do I force Wubi to download and install 32 bit version?](http://askubuntu.com/a/36831)
