### ISSUE TITLE
How to use local iso image without download

### ISSUE THREAD

**Issue by devhirano** [hakuna-m/wubiuefi#18]
I already downloaded ubuntu-16.04.1-desktop-amd64.iso in the same directory with wubi installer.
Although wubi downloaded iso image without it.

I think the image directory is C:\ubuntu\install, so I tried to copy it before and after run installer but both methods are failed.

So how can I force to use the downloaded iso image?

**Comment by hakuna-m** [comment]
The log file contains further information about the reason. 

You find the log file in the Windows temp folder. A shortcut for the Windows temp folder is `%temp%` . The path name for the log file is `%temp%\wubi-16.04.1-rev311.log if you use wubi16041r311.exe`. The full path name is something like `C:\Users\YourWindowsName\AppData\Local\Temp\wubi-16.04.1-rev311.log`.

**Comment by hakuna-m** [comment]
> So how can I force to use the downloaded iso image?

If checksum of your local copy doesn't match with checksum of Ubuntu release site, you can simply disconnect internet connection during Windows part of installation to skip internet verification.

But the reason is still interesting. A Wubi for 16.04.1 should check the correct iso for 16.04.1. Maybe, it is an older Wubi version for 16.04 ? Or the downloaded iso is a daily build from [here](http://cdimage.ubuntu.com/xenial/daily-live/current) but Wubi uses [this version] (http://releases.ubuntu.com/xenial) ?
> I think the image directory is C:\ubuntu\install, so I tried to copy it before

C:\ubuntu\install\installation.iso is the target iso after Windows part of installation, but every run of Wubi overwrites this iso. i.e. It is not a good location if you want to run Wubi again.

**Comment by devhirano** [comment]
I see, thanks.
I checked %temp%\wubi-16.04.1-rev311.log file and found a reason: didn`t match md5 sum.

```
    08-26 00:41 DEBUG  CommonBackend: Checking pre-specified ISO C:\Users\cube\Downloads\ubuntu-16.04.1-desktop-amd64.iso
    08-26 00:41 DEBUG  Distro:   checking Ubuntu ISO C:\Users\cube\Downloads\ubuntu-16.04.1-desktop-amd64.iso
    08-26 00:41 DEBUG  Distro:     does not contain casper\vmlinuz
    08-26 00:41 DEBUG  Distro:   checking Ubuntu ISO C:\Users\cube\Downloads\ubuntu-16.04.1-desktop-amd64.iso
    08-26 00:41 INFO   Distro: Found a valid iso for Ubuntu: C:\Users\cube\Downloads\ubuntu-16.04.1-desktop-amd64.iso
    08-26 00:41 DEBUG  CommonBackend: Searching for local CDs
    
    -- snip --
    
    08-26 00:42 ERROR  CommonBackend: Invalid md5 for ISO C:\Users\cube\Downloads\ubuntu-16.04.1-desktop-amd64.iso (17643c29e3c4609818f26becf76d29a3 != c94d54942a2954cf852884d656224186)
    None
```

So I re-downloaded iso from stable build(http://releases.ubuntu.com/16.04/ubuntu-16.04.1-desktop-amd64.iso) and Wubi used it correctly.

**Comment by hakuna-m** [comment]
@devhirano FYI: If you compare the md5 checksums with http://releases.ubuntu.com/xenial/MD5SUMS

The expected md5 checksum for **ubuntu-16.04.1-desktop-amd64.iso** was `17643c29e3c4609818f26becf76d29a3`. The existing md5 checksum was `c94d54942a2954cf852884d656224186`

Both checksums are valid:
`c94d54942a2954cf852884d656224186 *ubuntu-16.04-desktop-amd64.iso`
`17643c29e3c4609818f26becf76d29a3 *ubuntu-16.04.1-desktop-amd64.iso`

But the existing checksum was for **ubuntu-16.04-desktop-amd64.iso**.

**Comment by zyf0330** [comment]
According to this link [download Ubuntu MATE](https://ubuntu-mate.org/download/), there is another md5 checksum `d17ad97753c756513e1c3add89ce6fa2f0db8c2fba690408a1e5eabc8e01311b`. Why?

**Comment by hakuna-m** [comment]
`d17ad97753c756513e1c3add89ce6fa2f0db8c2fba690408a1e5eabc8e01311b` is a SHA256 checksum. see [SHA](https://en.wikipedia.org/wiki/Secure_Hash_Algorithm) and [MD5](https://en.wikipedia.org/wiki/MD5) 

If you want to compare checksums for Ubuntu MATE 16.04.1, here are the links:
 
 * MD5 http://cdimage.ubuntu.com/ubuntu-mate/releases/16.04.1/release/MD5SUMS
 * SHA256 http://cdimage.ubuntu.com/ubuntu-mate/releases/16.04.1/release/SHA256SUMS

**Comment by zyf0330** [comment]
Sorry, I am fooled just. Thanks
