### ISSUE TITLE
Can not download 18.04.2 release

### ISSUE THREAD

**Issue by linhndd** [hakuna-m/wubiuefi#180]
Please take a look it. I used wubi18042r333.exe and setup ubuntu. But it can not download and show error messenger http://prntscr.com/qdacwg

I getting file log below. 
[wubi-18.04.2-rev333.log](https://github.com/hakuna-m/wubiuefi/files/3985879/wubi-18.04.2-rev333.log)

Please help me fix it or how to fix it?

Thank you so much

**Comment by tomjohnston22** [comment]
Same issue for me for some time now. I can't install at all on Win10 on any of my PCs

**Comment by hakuna-m** [comment]
The download site has been changed. 

There is still a download site for 18.04.2:

http://old-releases.ubuntu.com/releases/18.04.2/

There is also a download link for the iso:

http://old-releases.ubuntu.com/releases/18.04.2/ubuntu-18.04.2-desktop-amd64.iso

But a necessary meta link does not contain 18.04.2:

http://old-releases.ubuntu.com/releases/18.04.2/MD5SUMS-metalink

> `12-20 05:22 ERROR  CommonBackend: Could not find ubuntu-18.04.2-desktop-amd64.metalink in metalink md5sums)`

So the best solution is that I will release a version for the current [18.04.3](http://releases.ubuntu.com/18.04.3/).

But it should be still possible to [manually download an iso](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-can-i-download-an-iso-manually) and [install it](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-use-a-pre-downloaded-iso-file-).

**Comment by tomjohnston22** [comment]
I can wait until 18.04.3. For what its worth I had the same issue with 19.x releases as well. Thanks for the work you do.

**Comment by linhndd** [comment]
> The download site has been changed.
> 
> There is still a download site for 18.04.2:
> 
> http://old-releases.ubuntu.com/releases/18.04.2/
> 
> There is also a download link for the iso:
> 
> http://old-releases.ubuntu.com/releases/18.04.2/ubuntu-18.04.2-desktop-amd64.iso
> 
> But a necessary meta link does not contain 18.04.2:
> 
> http://old-releases.ubuntu.com/releases/18.04.2/MD5SUMS-metalink
> 
> > `12-20 05:22 ERROR  CommonBackend: Could not find ubuntu-18.04.2-desktop-amd64.metalink in metalink md5sums)`
> 
> So the best solution is that I will release a version for the current [18.04.3](http://releases.ubuntu.com/18.04.3/).
> 
> But it should be still possible to [manually download an iso](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-can-i-download-an-iso-manually) and [install it](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-use-a-pre-downloaded-iso-file-).

Thank you so much. I can install 18.04 by shortcut command
