### ISSUE TITLE
Problem with disk size

### ISSUE THREAD

**Issue by nygage** [hakuna-m/wubiuefi#184]
Hello, I installed wubi 18.04 under Windows 10, i gave ubuntu a size of 64gb.
My surprise was today when i was working it says it has no more space, I checked the disk and it says it has 38gb only, why?
And now, i cant enter in Ubuntu because i have no space, i have important things there, what can i do?

Thanks a lot

**Comment by hakuna-m** [comment]
> I checked the disk and it says it has 38gb only, why?

How did you check the disk ? e.g Try to type 
`df -h`
in a [terminal](https://ubuntu.com/tutorials/command-line-for-beginners#3-opening-a-terminal).

The line with the slash (/) on the right side is the important one
 `/dev/loop0       35G     28G  5,4G   84% /`
It is the space which is avallable within **/ubuntu/disks/root.disk**. If there is no space available, there are warnings and error messages.

There is also a line with **/host** on the right side. **/host** is the Windows drive which contains root.disk with Ubuntu.

So if you need more space for system files, you can increase the size of **/ubuntu/disks/root.disk** which decreases the size of available space on Windows drive. see [ResizeandDuplicateWubiDisk](https://help.ubuntu.com/community/ResizeandDuplicateWubiDisk) or  [ResizeWubiDisk](https://help.ubuntu.com/community/ResizeWubiDisk)

Note: It is also possible to store non system files like videos, documents, pictures, music files...  directly on Windows drive (/host), so it is often not necessary to expand space for system files.

> And now, i cant enter in Ubuntu because i have no space,

In most cases it is possible to enter for command line which provides the command which I described above. 

>  have important things there, what can i do?

Important things without backups ? A backup of **/ubuntu/disks/root.disk** is always a good idea.

**Comment by nygage** [comment]
Yes, it's seems to be full, i dont know here, but its full haha. 

` /dev/loop0        62G    58G  209M 100% /`

Yes, i have the backup of the root.disk, i access ubuntu as safe boot.
I want to to this [ResizeandDuplicateWubiDsik](https://help.ubuntu.com/community/ResizeandDuplicateWubiDisk), but i was reading the maximum size is 32gb, is this correct? There is a flag but there is no warranty.

Thanks for your quick help

**Comment by nygage** [comment]
I think this is solved the problem was the Docker build cache, so be careful with that, 40gb in cache.
Thanks!
