### ISSUE TITLE
[Question] How can I install Ubuntu 19.10 and Kubuntu 19.10 on the same device?

### ISSUE THREAD

**Issue by ssense1337** [hakuna-m/wubiuefi#189]
I installed Ubuntu 19.10 using wubiuefi. How can I install Kubuntu 19.10 on the same device ?
I really appreciate any help you can provide !

**Comment by hakuna-m** [comment]
see #79 

It is also possible to upgrade branch for 2nd install. As Ubuntu 20.04 LTS is due to be released on April 23, 2020 , the upgrade should be for 20.04.

**Comment by NetnetZ** [comment]
Thank you so much! I will be waiting.

**Comment by hakuna-m** [comment]
see [2004r339-2](https://github.com/hakuna-m/wubiuefi/releases/tag/2004r339-2)
