### ISSUE TITLE
Make script tries to download from a 404 link 

### ISSUE THREAD

**Issue by freechelmi** [hakuna-m/wubiuefi#19]
Just trying to run make : 

--2016-08-28 15:01:01--  http://mock.googlecode.com/files/mock-0.3.1.zip
Résolution de mock.googlecode.com (mock.googlecode.com)… 74.125.71.82, 2a00:1450:400c:c0b::52
Connexion à mock.googlecode.com (mock.googlecode.com)|74.125.71.82|:80… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
2016-08-28 15:01:02 erreur 404 : Not Found.

Possible solution : 

- cache needed version on git repo if needed
- Use some working url like https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mock/mock-0.3.1.zip

**Comment by hakuna-m** [comment]
Thank you for reporting the issue. Because the downloads are only needed if you create a new environment for Wubiuefi development, I don't notice soon if urls have been changed.

IMHO the easiest solution at the moment is your second suggestion:

> - Use some working url like https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mock/mock-0.3.1.zip

I will add a fix in the next release:
```
--- a/tools/check_wine
+++ b/tools/check_wine
@@ -19,7 +19,7 @@ subprocess_url="http://effbot.org/media/downloads/subprocess-0
 subprocess_md5="00a249ec321786b17b8bb87a4eebcaeb"
 
 # Unit test stuff
-mock_url="http://mock.googlecode.com/files/mock-0.3.1.zip"
+mock_url="https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mock/mock-0.3.1.zip"
 mock_md5="b9f800d9908c158b1e67149e1508571b"
 
 # Ubuntu packages for mingw32
```

**Comment by freechelmi** [comment]
Great !
also I would say that a 'make clean' should remove also the wine directory, I had to remove it manually to force the new URL

**Comment by hakuna-m** [comment]
> also I would say that a 'make clean' should remove also the wine directory

On my experience it is often useful that 'make clean' doesn't remove wine directory. e.g. If you only want to clean your directories for building wubi.exe without removing programs for development. But you are right, there should be a way with 'make' to remove also wine directory.

Maybe a new 'make distclean' would be a solution. Another (additional) solution would be to check not only if a wine directory exists. So it would be possible for 'make' to continue with downloading and installing of missing programs.
