### ISSUE TITLE
wubi for ubuntu 20.04?

### ISSUE THREAD

**Issue by IDK61** [hakuna-m/wubiuefi#191]

**Comment by mreymann** [comment]
Yeah, waiting for it as well :-)

**Comment by hakuna-m** [comment]
As a final Ubuntu version always uses new download links which we want to test, we plan to release Wubiuefi for 20.04 some hours after release date of Ubuntu.

**Comment by IDK61** [comment]
> As a final Ubuntu version always uses new download links which we want to test, we plan to release Wubiuefi for 20.04 some hours after release date of Ubuntu.

Then when will you release wubi 20.04?

**Comment by hakuna-m** [comment]
> Then when will you release wubi 20.04?

in few hours = today or tomorrow

**Comment by IDK61** [comment]
> > Then when will you release wubi 20.04?
> 
> in few hours = today or tomorrow

:)

**Comment by hakuna-m** [comment]
[Wubi for Ubuntu 20.04 (rev. 339)](https://github.com/hakuna-m/wubiuefi/releases/tag/2004r339)

**Comment by Abdulrahman402** [comment]
> [Wubi for Ubuntu 20.04 (rev. 339)](https://github.com/hakuna-m/wubiuefi/releases/tag/2004r339)

I still have the same issue !!!

**Comment by hakuna-m** [comment]
> > [Wubi for Ubuntu 20.04 (rev. 339)](https://github.com/hakuna-m/wubiuefi/releases/tag/2004r339)
> 
> I still have the same issue !!!

The issue here was that there was no Wubiuefi version for 20.04. That issue has been fixed.

Maybe, tit is another known issue. e.g. #193 or #194 

If it is a new issue please create a new issue report.

**Comment by hussam93sh** [comment]
The installation stops immediately when it is running

**Comment by hussam93sh** [comment]
Please I want a solution quickly I cannot install Ubuntu version 20.04
 The install stops when wubi exe is running

**Comment by hussam93sh** [comment]
Please when this problem will be solved
