### ISSUE TITLE
MOK manager says only der encoded files are supported

### ISSUE THREAD

**Issue by IJR222** [hakuna-m/wubiuefi#194]
I cannot install due to the fact that my computer provides the error shown above

**Comment by hakuna-m** [comment]
It seems that MokManager 15 used in Ubuntu 20.04/18.04.4 has a bug. So it is necessary to downgrade to MokManager 13 used in Ubuntu 18.04 for Secure Boot support with our .cer file.

So I will blacklist MokManager 15 and create new packages with MokManager 13.

see similar issues of other projects: https://github.com/rhboot/shim/issues/143

**Comment by IJR222** [comment]
thank you, i have just disabled secure boot. I think disabling is easier. Solved!

**Comment by milankragujevic** [comment]
Hi, any info? I have the same problem. How can I downgrade MOKManager on 20.04?

**Comment by hakuna-m** [comment]
> How can I downgrade MOKManager on 20.04?

 Copy the ISO from **C:\ubuntu\install\installation.iso** to a place outside of folder ubuntu. So you can uninstall Wubiuefi without deleting the downloaded ISO of 20.04. Then use [1910r338](https://github.com/hakuna-m/wubiuefi/releases/tag/1910r338) with the [pre-downloaded ISO](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-use-a-pre-downloaded-iso-file-).

OR

Just disable SecureBoot. see [here](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-change-uefi-firmware-settings-from-windows-). 

As there seems to be no need for a hot fix, we plan to fix it with the next release.

**Comment by milankragujevic** [comment]
Hi. Thank you for the quick reply. I'll try and let you know. I cannot disable SecureBoot because my laptop is work-provided and it's BIOS is completely locked. I cannot even boot from USB. It's a Thinkpad T590.

**Comment by milankragujevic** [comment]
It worked! Thank you so much! 👍
