### ISSUE TITLE
update to 20.04

### ISSUE THREAD

**Issue by nexoone7** [hakuna-m/wubiuefi#196]
my ubuntu running 19.10 can i update with ubuntu updates 19.10. to 20.04 ???

**Comment by hakuna-m** [comment]
An upgrade from 19.10  to 20.04 should be possible like other upgrades in the past. see [here](https://help.ubuntu.com/community/FocalUpgrades).

Before upgrading, it is always recommended that you backup your folder ubuntu (at least **ubuntu\disks\root.disk**) from Windows.
 
If you also plan an upgrade from 18.04 to 20.04 (not necessary for 19.10) see https://github.com/hakuna-m/wubiuefi/issues/169#issuecomment-554047703

**Comment by nexoone7** [comment]
Thanks for the help realy same issue facing on during i update 19.4 to 9.10 but now i try all safety methods provided by your link 
Thankyou for help
