### ISSUE TITLE
Correct Partition not showing in installer

### ISSUE THREAD

**Issue by SuperSlimey5** [hakuna-m/wubiuefi#199]
Every time I start the Wubi installer it only shows one of my drives when I have a drive I partitioned for ubuntu.

Please help, I'm trying to install ubuntu 18.04.4

**Comment by hakuna-m** [comment]
> when I have a drive I partitioned for ubuntu.

Wubi(uefi) uses only Windows partitions. A partition for Windows contains a Windows file system (e.g. NTFS). The goal of Wubi is that you don't need to partition your disk which is already used for Windows. Of course, it is possible to use not only Windows drive C: if other Windows drives exist (drive d: e: and so on). 

If a Wubi(uefi) does not show a Windows drive, the log (see [here](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-are-the-logs-for-wubiuefi-)) should contain the reason (out of space, wrong file system)

But if you want Ubuntu on its own partition with a Linux file system (e.g. ext4), please use the standard installation of Ubuntu. see e.g. https://ubuntu.com/tutorials/tutorial-install-ubuntu-desktop#1-overview
