### ISSUE TITLE
How to use a pre-downloaded iso ?

### ISSUE THREAD

**Issue by JohnyMac** [hakuna-m/wubiuefi#2]
I have downloaded an ISO from the official download in ubuntu site so I don't need to redownload it, Any way to manually set the ISO ?

Thanks.

**Comment by hakuna-m** [comment]
The easiest way is to put desktop iso and wubi.exe in the same folder and run wubi.exe from this location.

Another possibilty is to [open a "command prompt" as administrator](http://www.howtogeek.com/194041/how-to-open-the-command-prompt-as-administrator-in-windows-8.1) and type:

    path_of_wubi.exe --isopath=path_of_iso

e.g.:

    C:\Users\Username\Downloads\wubi14044r302.exe --isopath=C:\Users\Username\Downloads\ubuntu-14.04.4-desktop-amd64.iso

**Comment by JohnyMac** [comment]
Oh thanks, I put the ISO in the same folder but it didn't work, I just added the argument --32bit and it worked. (What a simple solution lol)
Thanks for this.

BUT, I have a problem, Not directly related to Wubiuefi.
When I restart and then choose to boot from the Ubuntu, Some error appears from *wubildr.mbr*..
Any idea what is that ?

**Comment by hakuna-m** [comment]
> I just added the argument --32bit and it worked. (What a simple solution lol)

This means that you have a 64 bit CPU and you downloaded a 32 bit iso. Wubi always tries to download the matching architecture. It does not matter if you have a 32 bit Windows.  It is a simple solution to use a pre-downloaded 32 bit iso but not always the best solution. If you need UEFI support, IMHO a 64 bit iso is always the better choice.

> However, I have a problem, Not directly related to Wubiuefi.

This means that you did not use Wubiuefi !? Which Wubi version and which Ubuntu version did you use ? Do you use a computer with a pre-installed Windows 8, 8.1 or Windows 10 which are always installed in UEFI mode.

> Some error appears from wubildr.mbr..

Do you mean something like [this](https://github.com/hakuna-m/wubiuefi/wiki#uefi) ?

**Comment by JohnyMac** [comment]
> This means that you have a 64 bit CPU and you downloaded a 32 bit iso. Wubi always tries to download the matching architecture. It does not matter if you have a 32 bit Windows. It is a simple solution to use a pre-downloaded 32 bit iso but not always the best solution. If you need UEFI support, IMHO a 64 bit iso is always the better choice.

Umm, Well, The computer is 32 bit, Dunno why was it forcing a 64... And also, I don't really know what is UEFI but I am pretty sure I have just the normal old booting.. AFAK, Its called **legacy boot** ?
I have windows xp and windows 7 pre installed, And I want to install ubuntu with them.

And yes, The error is just like this one here: https://github.com/hakuna-m/wubiuefi/wiki#uefi
Not sure if the number was exactly that though :P

**Comment by hakuna-m** [comment]
> Umm, Well, The computer is 32 bit, Dunno why was it forcing a 64...

The log should answer the questions. The location of the log file is [the temporary folder](http://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/where-is-the-temporary-folder/44a039a5-45ba-48dd-84db-fd700e54fd56).  e.g.: c:\users\username\appdata\local\temp\wubi-14044-rev302.log

If you find a line with

    WindowsBackend: arch=amd64

a 64 bit CPU was detected. This means you can use a 64 bit iso. Maybe, it sounds a little bit strange if you use an old 32 bit Win XP. But Ubuntu (also installed by Wubi) does not use Windows drivers for hardware access, so it is possible if your hardware supports 64 bit. I do not think that the detection is wrong. If you do not trust it you can read the line with the processor name

    WindowsBackend: processor_name= ......

and manually check the abilities. 

>  I am pretty sure I have just the normal old booting..

I was not pretty sure but I did not know anything about your configuration. But if you use a new Wubi version, an error of wubildr.mbr also indicates that you do not use UEFI.

> Not sure if the status was exactly that though :P 

Is it difficult for you to get the exact status code? Which system enviroment does the Wubi log show ?

e.g.:

    DEBUG  WindowsBackend: system_drive=Drive(C: hd 184674.480469 mb free ntfs)
    DEBUG  WindowsBackend: drive=Drive(C: hd 184674.480469 mb free ntfs)
    DEBUG  WindowsBackend: drive=Drive(D: cd 0.0 mb free )

**Comment by JohnyMac** [comment]
Well, Looks like the computer IS really 64 bit, lol.. This is embarssing but tbh, I never knew until now..
There is reasons but hard to explain.. xD, Simply, Its not my computer.

Soo, I just uploaded the full logs here: http://pastebin.com/HiHp8NXN
C:/ Is where I have windows XP installed.
J:/ Is where I have windows 7 installed and also where I ran the wubi installion.
And Ubuntu have been installed to K:/.

**Comment by hakuna-m** [comment]
> `02-23 17:04 INFO   root: === wubi 14.04 rev286 ===`

**rev286** is not a new version of the project wubiuefi. IMHO there is no advantage for your current issue in using the new project versions but other issues are fixed. So do not wonder if you'll get ["serious errors"](http://askubuntu.com/questions/453411/ubuntu-14-04-not-booting-after-error-message-tmp-could-not-be-mounted) with old Wubi versions.

But, maybe other logs of other Wubi versions exist. The log says that finally, you uninstalled this Wubi version 

>  `WindowsBackend: Removing bcd entry {7f811962-d838-11e5-a8c0-c10496bc18ef}`

and that you installed to J: 

> `WindowsBackend: Installing into J:\ubuntu`

and not K: as expected:

> And Ubuntu have been installed to K:/.

For your current issue:

> The error is just like this one here: https://github.com/hakuna-m/wubiuefi/wiki#uefi

Try to check with [bcdedit](https://technet.microsoft.com/en-us/library/cc731662.aspx) or [EasyBCD for non-UEFI systems](http://neosmart.net/EasyBCD) if the Windows drive (partition) of the BCD entry matches with the real location of your wubildr.mbr. See [here](http://www.howtogeek.com/howto/20340/how-to-restore-the-wubi-ubuntu-bootloader) 

In a second step wubildr.mbr tries to run wubildr. IMHO wubildr should be also available at the root directory of your Windows drive. The **path \ubuntu\winboot\wubildr** is not part of the search path of wubildr.mbr.

**Comment by JohnyMac** [comment]
Ok, soooo, It worked by itself after leaving it for some days.. I surely did something to make it work but don't know lol... Anyways, Thanks a lot for your help :+1:
