### ISSUE TITLE
Install is Hanging when Booting into Ubuntu - Lenovo Miix 10 Tablet

### ISSUE THREAD

**Issue by raducreanga** [hakuna-m/wubiuefi#200]
I am sorry to revive an old issue, but have the exact same problem as described in a previous issue:  [https://github.com/hakuna-m/wubiuefi/issues/57](url)
Briefly, I am trying to install Lubuntu 16.04.6 32bit, with Wubi 16046r333. Everything works fine in Windows but, after reboot, it is hanging and never booting, exactly as described in the thread above. 
I do have access to GRUB menu, but I literally tried every option without any success.
It might have something to do with the fact that, if I am not mistaken, the tablet has sort of a 64 bit UEFI (no legacy BIOS) and a 32 bit Intel Atom CPU.
The exact and complete specs are to be found here: [https://www.cnet.com/products/lenovo-miix-10-10-1-atom-z2760-2-gb-ram-64-gb-ssd/](url)
Is there anything I could do to install any version of Ubuntu (preferably a lightweight one) on this tablet? I have been trying, on and off, for more than 2 years and I was really hoping to get it done this time, with the help of wubiuefi.
Needless to say the tablet is useless with Windows 10. Even if it works, it is so slow that you basically cannot do anything productive.

**Comment by hakuna-m** [comment]
> I was really hoping to get it done this time, with the help of wubiuefi.

Wubiuefi has its own GRUB boot loaders for 32 bit or 64 bit UEFI firmware. So Wubiuefi can help to boot into a GRUB boot menu even if the downloaded ISO contains no matching boot loader.

But it is still necessary that the ISO contains a working Linux kernel with all needed drivers for your system.

As described in #57 and [here](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-set-boot-options-), it helps sometimes to change boot options.

There are existing menu entries with frequently used boot options, but the menu entries do not contain all possible boot options.

Maybe, boot options of similar models do work. e.g. https://esc.sh/blog/linux-on-lenovo-miix-320/ 

If you edit the "Intel graphics workarounds" line: 

> Above the line that starts with linux, add the following
> `set gfxpayload=keep`

Replace `i915.modeset=0` with 

> `nomodeset i915.modeset=1 fbcon=rotate:1`

But as I have no experience with your tablet, I don't know if there are any boot options which work. 

Maybe, you also find some ISOs with a customized kernel and drivers. 

Unfortunately, at that point the issues depend on Linux and do not depend on Wubiuefi.

**Comment by raducreanga** [comment]
Thank very much for your time and clarifications.

I tried editing the "Intel graphics workarounds" as you indicated, but with no effect.
It still freezes when booting the modified line. It just adds a message "Booting a command list" to the black screen and then an underscore character that was also displayed with the original boot options and then everything freezes. Not even <CTRL>+<ALT>+<DEL>  works.

Thank you also for the other suggestion, concerning the Linux distro.
Just to clarify, Miix 320 is not that similar to Miix 10, since 320 has a 64-bit processor (so a lot of newer Linux 64-bit distros should work) but the tablet I have has a 32-bit one.

I will keep trying and if I succeed, I will post the solution.

**Comment by raducreanga** [comment]
"Not even ++ works."
Not even ctrl+alt+del works...

**Comment by hakuna-m** [comment]
> Just to clarify, Miix 320 is not that similar to Miix 10, since 320 has a 64-bit processor (so a lot of newer Linux 64-bit distros should work) but the tablet I have has a 32-bit one.

The workaround for Miix 320 does not use boot options for a 64-bit processor. e.g. [nomodeset](https://askubuntu.com/questions/207175/what-does-nomodeset-do) is an option for video drivers.

IMHO, the 32/64 bit issues are solved with Wubiuefi because it can use a different architecture for boot loader and kernel.

It uses always a 32 bit boot loader for legacy BIOS.
It uses a 32 bit EFI boot loader if Windows uses one.
It uses a 64 bit EFI boot loader if Windows uses one.

It uses a 64 bit kernel if your CPU supports it by default.
It uses a 32 bit kernel if your CPU does not support 64 bit or if you overrule the default value.

> Not even ctrl+alt+del works...

Try [ALT+Sysrq+REISUB](https://en.wikipedia.org/wiki/Magic_SysRq_key)

**Comment by raducreanga** [comment]
> IMHO, the 32/64 bit issues are solved with Wubiuefi because it can use a different architecture for boot loader and kernel.

This is why I had so much hope for this solution, it seemed the perfect tool to do the job.
Unfortunately, I've tried everything that you indicated and I still failed.
I've tested several different distros, even some that where designed to work on older systems and that are recognised for starting "on almost anything". The install seems to work perfectly from Windows for any Ubuntu flavor. It detects every variation (ubuntu, lubuntu, wubi, wubi lz, wubi gz, wubi EFI), as I am sure that you already know.
However, on reboot, after the GRUB menu, no matter what I try to tinker, It still freezes completely.

> Try ALT+Sysrq+REISUB
Not even this works.

I have the feeling that it freezes the moment it tries to load the kernel but I really have no way of confirming it. The verbose mode does not yield anything either.

However, using GRUB command (ls /), I got the feeling that the root partition is set to the one that has Windows 10. Despite that, if I try to start the Windows 10 system, I need to set the root to another partition, the one including the EFI directory, that also includes a ubuntu sub-directory. I admit to not having entirely grasped the concept of EFI boot, but maybe there is something around this matter that its not working as expected.

Any insight is greatly appreciated.

Thank you!

**Comment by raducreanga** [comment]
After deep diving in all sorts of Linux distros and countless forums, I reached a bitter conclusion. 

First of all, I must correct one of my previous statements: the tablet has a 32-bit UEFI (no legacy BIOS) but also a 32-bit processor. This is one of the main problems, since almost no 32-bit distro has by default a 32-bit UEFI. Most distros don't even have a 32-bit implementation anymore. However, there are still a few with both, such as Sparky Linux, MX Linux, Arch Linux and a few others.
Also, this is something that Wubiuefi can really help with. At least the 16046r333 release, that relies on the last 32-bit Ubuntu version 16.04.x. One way or another, either booting one of the 32-bit distros with 32-bit UEFI from an USB drive or, more comfortably, using Wubiuefi, you can reach the initial GRUB screen.

The real problem starts there. The best way to describe it can be summed up like this: _"The 1st-generation 2012-released Intel Atom Clover Trail Z2760 Win 8 touchscreen tablets likely cannot run Linux, mainly because of the very proprietary mobile PowerVR GPU from Imagination Technologies (contracted by Intel), ie no Linux drivers available = blank screen when booted."_
More details here: [https://forums.linuxmint.com/viewtopic.php?t=250910](url)

So everything boils down to this: is there a Linux kernel that supports PowerVR GPU? Not that there would be a real need for such a kernel to exist, but I still hope I am not the only one obsessing over this.
If you or anybody could answer this question, I would be deeply grateful.

Nevertheless, thank you very much for all the work you invested in Wubiuefi, which I honestly find an excellent solution.

**Comment by raducreanga** [comment]
Since the issue is not related to wubiuefi, I don't see any point in leaving it open.
