### ISSUE TITLE
Is it safe to skip this?

### ISSUE THREAD

**Issue by playsenge** [hakuna-m/wubiuefi#211]
Hi,
I kinda know some stuff about Linux, but I actually used it only once.
Is it safe to skip this?
"No EFI System Partition was found. This system will likely not be able to boot successfully, and the installation process may fail."
I don't have a pendrive to fix the boot manager in case something fails, so I just wanna be sure.

Thanks!
senge

**Comment by hakuna-m** [comment]
As it is a known issue with a workaround for Ubuntu (see [release notes](https://github.com/hakuna-m/wubiuefi/releases/tag/2004r339)), the workaround (skipping with "Continue") has been tested for a lot of systems with different configurations until now.

As far as I know, there are no reports about installations which leave an unbootable Windows. Additionally, the warning message is a message of the standard Ubuntu installer and not one of Wubiuefi. For Wubiuefi, the Ubuntu installer needs no EFI partition to install a boot loader. Wubiuefi uses the Windows Boot Manager and a customized boot loader for Ubuntu.

So skipping of the known messages should be safe.

In general, there has never been a 100% warranty that a system program which e,g. adds entries to the Windows Boot Manager has no negative side effects. It is not possible to test all possible configurations. So it is always a good idea to frequently backup important data.

**Comment by playsenge** [comment]
Thanks!
