### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by playsenge** [hakuna-m/wubiuefi#212]
![20200623_202127](https://user-images.githubusercontent.com/40773107/85441319-3dccbc80-b58f-11ea-9d93-2b8031dc9d4d.jpg)
the ubuntu installation progress bar ended
now i have this
what do i do
help quick

**Comment by hakuna-m** [comment]
IMHO, it is a known issue of 20.04 see #193 

There are always some messages immediately before rebooting.

The known issue is the need for a manual reboot. Pressing the key sequence REISUB with [Magic SysRq key](https://en.wikipedia.org/wiki/Magic_SysRq_key) helps.
