### ISSUE TITLE
How to open root.disk from Windows 7

### ISSUE THREAD

**Issue by MarcosLp69** [hakuna-m/wubiuefi#216]
i have an Ubuntu MATE 20.04 installation with wubi, i already tried Explorer2fs and Ext2explore, in Ext2explore i was able to see the folders and files from the root directory, but couldnt see the contents

**Comment by hakuna-m** [comment]
Try [7-Zip](https://www.7-zip.org/) which can also read Wubi disks which are created by Ubuntu 20.04.

**Comment by MarcosLp69** [comment]
thanks!
