### ISSUE TITLE
The attempt to mount a file system with type swap at none failed - Ubuntu 20.04 rev339

### ISSUE THREAD

**Issue by JakobJohannes** [hakuna-m/wubiuefi#224]
Hello!
After successfully installing Linux Ubuntu wit wubi2004v339.exe (ubuntu-20.04-desktop-amd64.iso) using 128 GB installation size I got from one day to the other suddenly booting to initramfs. When exiting this mode kernel panic occourred. I decided to uninstall the Ubuntu installation with "uninstall-wubi.exe" and then reinstalling using again wubi2004v339.exe. Now I get the error message: 
"The attempt to mount a file system with type swap in /host/ubuntu/disks/swap.disk at none failed. You may resume partitioning from the partitioning menu."
 
I found the same message in #125, but the solution there does not work for me, as my second disc (which is not a SSD) is not a "dynamc disc" but "basic". Nevertheless I tried installation with taking my second disc offline, but again the same error message occourred.
If additional information is needed, I will be happy to provide it.
(Error messages are in German - if you need f.ex. screenshots.)
Any help would be much appreciated!

Regards
Jakob

--------------------------------------
edit @hakuna-m : fixed URL

**Comment by hakuna-m** [comment]
> I found the same message in #125, but the solution there does not work for me, as my second disc (which is not a SSD) is not a "dynamc disc" but "basic".

IMHO, the reason for #125 was the Dynamic Disk. Is your first disk a Dynamic Disk ? Are there compressed, encrypted or virtual drives on Windows ?

Probably, some Windows settings for your drives are not compatible with a Wubiuefi installed Ubuntu.

**Comment by JakobJohannes** [comment]
Thank you for your answer! I decided to paste the disc management window in this message, may be you see more than I do:
![grafik](https://user-images.githubusercontent.com/68547785/88063034-e0199900-cb69-11ea-8585-f6a8e081fa5f.png)

**Comment by hakuna-m** [comment]
Which drive does contain the folder ubuntu ? C: ? Is the NTFS compression enabled (it should be disabled) ? see e.g. https://www.windowscentral.com/how-use-ntfs-compression-windows-10

How does Ubuntu detect your Windows drives ?  https://github.com/hakuna-m/wubiuefi/issues/125#issuecomment-449570677

**Comment by JakobJohannes** [comment]
Thank you for your quick response! Concerning your questions:
- folder ubuntu is in C:
- I tested all partitions that are available in Windows (C:, D:, F:) - no partition has NTFS compression enabled - here especially drive C:
![GitHub_LW_C_nicht_komprimiert](https://user-images.githubusercontent.com/68547785/88089778-e1a88880-cb8c-11ea-8ff2-b17424fe079c.jpg)
  Drive G: is not formatted (RAW)
- and here the output from "parted --list" and "df -h", after I booted into "demo mode":
![Bildschirmfoto von 2020-07-21 17-24-19](https://user-images.githubusercontent.com/68547785/88090237-9478e680-cb8d-11ea-892a-70c3d703a693.png)

**Comment by JakobJohannes** [comment]
Success!! I found a simple workaround: I installed Ubuntu in drive F: - that worked without problems. The only problem that remains is that I explicitly wanted to install Ubuntu in drive C:, as there are all my program files; drive F: is for data.

**Comment by hakuna-m** [comment]
> * I tested all partitions that are available in Windows (C:, D:, F:) - no partition has NTFS compression enabled - here especially drive C:

It is also possible to compress folders without compressing the whole drive, but probably there is another reason for your issue on drive C:

Maybe, a Windows update enabled hibernate. That can cause initramfs errors as you wrote above:

> I got from one day to the other suddenly booting to initramfs.

It is also described [here](https://github.com/hakuna-m/wubiuefi/issues/29#issuecomment-263599871) with a screenshot.

But your swap.disk error is not reported for the hibernate issue.

**Comment by JakobJohannes** [comment]
Perfect! I switched off hibernate mode and now I could install Ubuntu in drive C: ! 
But trying to reproduce the initramfs error I was not so successful... although switching on hibernate mode again I could boot to Ubuntu. May be it takes some more reboots until such an error would occur again? 
Nevertheless thank you for your kind support.

**Comment by hakuna-m** [comment]
> May be it takes some more reboots until such an error would occur again?

`powercfg /h off `

turns off hibernation and all similar Windows features completely. But it is also possible to disable features like "Fast Startup" individually. 

see [answer at askubuntu](https://askubuntu.com/a/145904)

**Comment by JakobJohannes** [comment]
Thanks again for your kind support! My installation now runs better than before (especially the boot screen and the background right click menu that didn't work as expected)!
