### ISSUE TITLE
20.04 installer no longer works

### ISSUE THREAD

**Issue by vernike490** [hakuna-m/wubiuefi#226]
The 20.04 installer no longer works as canonical has removed 20.04 and now have 20.04.1

08-08 08:41 DEBUG  TaskList: ### Running get_metalink...
08-08 08:41 DEBUG  downloader: downloading http://releases.ubuntu.com/20.04/ubuntu-20.04-desktop-amd64.metalink > C:\ubuntu\install
08-08 08:41 ERROR  CommonBackend: Cannot download metalink file http://releases.ubuntu.com/20.04/ubuntu-20.04-desktop-amd64.metalink err=[Errno 14] HTTP Error 404: Not Found
08-08 08:41 DEBUG  downloader: downloading http://cdimage.ubuntu.com/daily-live/pending/focal-desktop-amd64.metalink > C:\ubuntu\install
08-08 08:41 ERROR  CommonBackend: Cannot download metalink file2 http://cdimage.ubuntu.com/daily-live/pending/focal-desktop-amd64.metalink err=[Errno 14] HTTP Error 404: Not Found
08-08 08:41 DEBUG  TaskList: ### Finished get_metalink

**Comment by vernike490** [comment]
Ubuntu mate works fine however

**Comment by Svahnen** [comment]
I just tried ubuntu mate, and got error that the logfile was already in use at the end of the installation and then the program just shuts off. Nothing happens on reboot, and if i run wubi again it says there is already and installation and asks me if i want to uninstall it.

Here is the logfile in question https://pastebin.com/5jfux6s5

**Comment by hakuna-m** [comment]
> The 20.04 installer no longer works as canonical has removed 20.04 and now have 20.04.1

I will release an upgrade for 20.04.1.

It should still work if you download the ISO manually. http://releases.ubuntu.com/20.04.1/ubuntu-20.04.1-desktop-amd64.iso

see [How can I use a pre-downloaded ISO file ?](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-use-a-pre-downloaded-iso-file)

**Comment by hakuna-m** [comment]
> I just tried ubuntu mate, and got error that the logfile was already in use at the end of the installation and then the program just shuts off. Nothing happens on reboot, and if i run wubi again it says there is already and installation and asks me if i want to uninstall it.

You got a download issue...

> DownloadError: rejected by tracker - Requested download is not authorized for use with this tracker. 

....and a subsequent message about the downloaded iso: 

> WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\ubuntu\\install\\ubuntu-mate-20.04-desktop-amd64.iso'

The download issue is probably a temporary issue: see https://askubuntu.com/a/884246
So you can try again after uninstalling the installed parts.

But maybe, it is better to wait for the Wubiuefi release for 20.04.1 with newer download links.

**Comment by hakuna-m** [comment]
> The 20.04 installer no longer works as canonical has removed 20.04 and now have 20.04.1

Unfortunately, it is not only a replacement. 20.04.1 has no metalinks. So it is necessary to change download steps.

**Comment by hakuna-m** [comment]
The new release [20041r341](https://github.com/hakuna-m/wubiuefi/releases/tag/20041r341) should fix all download issues which were reported above. 
```
09-06 18:10 DEBUG  downloader: downloading http://releases.ubuntu.com/20.04.1/ubuntu-20.04.1-desktop-amd64.list > C:\ubuntu\install
09-06 18:11 DEBUG  downloader: Download start filename=C:\ubuntu\install\ubuntu-20.04.1-desktop-amd64.list, url=http://releases.ubuntu.com/20.04.1/ubuntu-20.04.1-desktop-amd64.list, basename=ubuntu-20.04.1-desktop-amd64.list, length=20721, text=None
09-06 18:11 DEBUG  downloader: download finished (read 20721 bytes)
09-06 18:11 DEBUG  downloader: downloading http://releases.ubuntu.com/20.04.1/SHA256SUMS > C:\ubuntu\install
09-06 18:11 DEBUG  downloader: Download start filename=C:\ubuntu\install\SHA256SUMS, url=http://releases.ubuntu.com/20.04.1/SHA256SUMS, basename=SHA256SUMS, length=202, text=None
09-06 18:11 DEBUG  downloader: download finished (read 202 bytes)
09-06 18:11 DEBUG  downloader: downloading http://releases.ubuntu.com/20.04.1/SHA256SUMS.gpg > C:\ubuntu\install
09-06 18:11 DEBUG  downloader: Download start filename=C:\ubuntu\install\SHA256SUMS.gpg, url=http://releases.ubuntu.com/20.04.1/SHA256SUMS.gpg, basename=SHA256SUMS.gpg, length=833, text=None
09-06 18:11 DEBUG  downloader: download finished (read 833 bytes)
09-06 18:11 INFO   saplog: Verified a signature from ID:'D94AA3F0EFE21092'.
09-06 18:11 INFO   saplog: Checking block bindings..
09-06 18:11 INFO   saplog: Key verified successfully.
09-06 18:11 DEBUG  CommonBackend: metalink md5sums:
b45165ed3cd437b9ffad02a2aad22a4ddc69162470e2622982889ce5826f6e3d *ubuntu-20.04.1-desktop-amd64.iso
443511f6bf12402c12503733059269a2e10dec602916c0a75263e5d990f6bb93 *ubuntu-20.04.1-live-server-amd64.iso

09-06 18:11 DEBUG  TaskList: ### Finished get_metalink
```
The new method still checks hashsums of the iso file and verifies the signature of the hashsum file. As Ubuntu provides o
