### ISSUE TITLE
Lubuntu 16.10 fails because of missing packages on desktop ISOs

### ISSUE THREAD

**Issue by hakuna-m** [hakuna-m/wubiuefi#24]
Lubuntu 16.10 desktop ISOs do not contain **/pool** with additional deb packages. If you compare 
[lubuntu-16.10-desktop-amd64.list](http://cdimage.ubuntu.com/lubuntu/releases/16.10/release/lubuntu-16.10-desktop-amd64.list) and [ubuntu-16.10-desktop-amd64.list](http://releases.ubuntu.com/yakkety/ubuntu-16.10-desktop-amd64.list) e.g.

**/pool/main/g/grub2/grub-efi-amd64_2.02~beta2-36ubuntu11_amd64.deb** and
**/pool/main/l/lupin/lupin-support_0.57_amd64.deb** do not exist.

So installation without internet connection fails on EFI systems because of missing EFI GRUB packages. This is a general Lubuntu issue. 

But if you try it with internet connection, it seems to work but unfortunately, **lupin-support** package with GRUB configuration for Wubi is also not installed.

So booting into new installation doesn't work and additionally GRUB boot loader is installed on the wrong place. 

As workaround we will add package **lupin-support** to Wubiuefi file with the soon coming next release 1610r316.

**Comment by hakuna-m** [comment]
I added lupin-support package to version 1610r316. So we can avoid that Wubiuefi installs a boot loader with wrong configuration. i.e. If it installs a boot loader and a boot menu, it is on the right place and it should work.

But the new version doesn't fix issues caused by other missing packages on ISO. See reported Lubuntu 16.10 bugs:

 * [failed to install grub-efi-amd64-signed](https://bugs.launchpad.net/ubuntu/+source/grub-installer/+bug/1633913)
 * [grub-installer fails, can't dpkg remove grub-pc](https://bugs.launchpad.net/ubuntu/+source/grub-installer/+bug/1632560)

So our test results for Lubuntu 16.10 are:
 * 1610r316, legacy BIOS (non-UEFI), with internet connection during Linux part of installation (after reboot) -> works without problems
 *  1610r316, UEFI, with internet connection during Linux part of installation (after reboot) -> fails like [bug 1632560](https://bugs.launchpad.net/ubuntu/+source/grub-installer/+bug/1632560) but creates a working boot menu

**Comment by hakuna-m** [comment]
An additional note for users without internet connection during installation.

The workaraound for a grub error from [here (second possibility)](https://github.com/hakuna-m/wubiuefi/issues/42#issuecomment-287435194) works for the remaining grub errors, too.

**Comment by xkill** [comment]
Same problem with Lubuntu 16.04
