### ISSUE TITLE
Does it only work with Ubuntu? What about other Linux Distros?

### ISSUE THREAD

**Issue by DeadProgrammer0** [hakuna-m/wubiuefi#241]
I'm using Windows 10 and I want to Dual Boot Parrot OS. Is it possible with this program?

**Comment by hakuna-m** [comment]
To put in a nutshell, some Ubuntu based distros with Ubiquity installer work, other distros do no work.

I don't know, if Boot Parrot OS work, but probably it does not work.

Currently, we are testing a release with an Ubiquity independent installer. So probably in future releases there are more distros which should work.

**Comment by DeadProgrammer0** [comment]
Thank you for the information. I did install the Parrot OS manually using a Boot-able USB.
