### ISSUE TITLE
If i select to install kubuntu on my D drive, will it erase anything on my D drive or does it just create a new folder

### ISSUE THREAD

**Issue by BlueBurgersTDD** [hakuna-m/wubiuefi#251]
Title says it all

**Comment by hakuna-m** [comment]
Wubi(uefi) will create a folder (D:\ubuntu) and 2 files outside the folder (D:\wubildr, D:\wubildr.mbr) on D: drive only.

Kubuntu will be installed on a virtual disk which is a file on Windows drive (D:\ubuntu\disks\root.disk).

If you have no experience with Wubi(uefi), note that the Kubuntu version of the used installer has no progress bar during second part of installation. Maybe, that fact means that it is more tricky for you to install Kubuntu than Ubuntu.

**Comment by BlueBurgersTDD** [comment]
I tried installing Ubuntu but when its finished it just shown `initramfs unpacking failed: Decoding failed`. I could not do anything unplugging the PC. When i did that my PC was exactly like usual. Any ideas how to fix it?

**Comment by BlueBurgersTDD** [comment]
And yes, secure boot is off

**Comment by hakuna-m** [comment]
> it just shown `initramfs unpacking failed: Decoding failed`.

It is reported issue on Launchpad for Ubuntu. see https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1835660 
So it is a general issue.

But IMHO that issue has nothing to do with your issue(s). 

> I could not do anything unplugging the PC

see known issues from [release notes](https://github.com/hakuna-m/wubiuefi/releases/tag/20041r342
): --> "Manual reboot is necessary after second part of installation."

For manual reboot you can press the keys REISUB together with [Magic SysRq key](https://en.wikipedia.org/wiki/Magic_SysRq_key).

> When i did that my PC was exactly like usual.

After second reboot it is necessary to select "Ubuntu" from boot menu. see [Where is my Ubuntu entry in Windows Boot Manager for UEFI ?](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-is-my-ubuntu-entry-in-windows-boot-manager-for-uefi-)
