### ISSUE TITLE
I disabled secureboot for Ubuntu installation with your wubi and this Is what I get...

### ISSUE THREAD

**Issue by pitrako** [hakuna-m/wubiuefi#254]
initramfs unpacking failed: Decoding failed

And a lot of unintelligible text.

My machine Is a MSI "Infinite X Plus 9th":
- RTX 2080
- I7-9700K
- MAG Z390M MORTAR (Motherboard)
- Wubi for Ubuntu 20.04.1 (rev. 342)
- Using a TV via hdmi instead of a monitor.
EDITED:
![IMG_20201128_105536](https://user-images.githubusercontent.com/42267151/100499284-8f91f800-3168-11eb-9588-7e13a71b88ab.jpg)
EDITED AGAIN:
I inserted nomodeset and this is what It shows now:
![IMG_20201128_190150](https://user-images.githubusercontent.com/42267151/100522953-e4576200-31ac-11eb-861a-2b690c32e3a1.jpg)

**Comment by hakuna-m** [comment]
> initramfs unpacking failed: Decoding failed

It is a reported issue on Launchpad for Ubuntu. see https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1835660
So it is a general but harmless issue and has nothing to do with your issue.

> Could not find the ISO /ubuntu/install/ubuntu-20.04.1-desktop-amd64.iso

The default ISO name should be **/ubuntu/install/installation.iso**. Did you change the ISO name in [GRUB menu](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-set-boot-options-) ? 

Can you add your file **\ubuntu\install\boot\grub\grub.cfg** from Windows drive with Wubi-Installation. That file should contain the boot menu.

Please also add the log file. see [here](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-are-the-logs-for-wubiuefi-).

**Comment by pitrako** [comment]
I kinda solved It, tried installing It on letter D (HDD) instead of C (SSD) and with nomodeset inserted I was able to watch what was happening on screen, It installed correctly. Then I installed the nvidia drivers 455, reboot and problem solved, but I don't know why doesn't work with C, you can close this If you want, thanks.
