### ISSUE TITLE
USB not working in Windows 7 (x64) after restarting computer from Ubuntu

### ISSUE THREAD

**Issue by somsom37** [hakuna-m/wubiuefi#257]
_USB ports not working in Windows 7 (x64) after restarting computer from Ubuntu in Windows._
After rebooting back to Windows 7-64bit Prof., USB drivers stop working in Windows. Tried versions of wubi: wubi18045r333.exe and wubi20041r342.exe. In Ubuntu itself, everything is ok, but when you reboot back to Windows 7, all USB drivers "fall off" - that is, the USB drivers do not work. That is, there are drivers in the OS, but they are not working later - an error.
My OS is Windows 7 Professional 64-bit (like EFI). Only removing and reinstalling USB drivers helps. And since I have a mouse on the USB port, it is very problematic to do this through the keyboard%)))
My OS is Windows 7 Professional 64-bit (like EFI).
Sorry for bad English.

**Comment by hakuna-m** [comment]
Wubiuefi does not change the USB drivers for Windows. So there should be no direct connection beween Wubiuefi and your issue. 

Maybe, you connected USB devices during install which has changed the Windiows configuration. 

See https://answers.microsoft.com/en-us/windows/forum/windows_7-hardware/usb-mouse-not-detected-on-reboot/c48acdfa-95d8-4f63-9cc8-e76cb19da034

**Comment by somsom37** [comment]
No, I didn't connect anything during the reboot, even the computer was completely turned off. In general, this is a strange glitch, before this was not. And it was ok. And how can this affect GYI and also in Windows.

**Comment by hakuna-m** [comment]
> No, I didn't connect anything during the reboot, even the computer was completely turned off.

I didn't think that you connected some USB devices during reboot. But maybe, it was necessary to connect an USB storage device to back up Windows before installing or to connect an USB stick with a pre-downloaded ISO image....and so on. 

> And how can this affect USB and also in Windows.

I don't know. Your error report is the first one for Wubiuefi. e.g. I also use different USB mouses without any problems after installing Ubuntu with Wubiuefi.

But I know Windows users who had suddenly USB mouse issues . But these Windows users have never used Wubiuefi.......

**Comment by somsom37** [comment]
Regarding EFI / UEFI, I don't remember exactly how I installed Windows at that time, I had an EFI folder on my C: drive. Now this folder does not exist, recently I reinstalled Windows again.
that is, with this EFI / UEFI I can and will be mistaken.
I tried to put Ubuntu again after. So another problem is with the monitor, the computer and the monitor are already old. I could not check what and how - the black screen was in logon - when entering the user and password in Ubuntu .. That is, I could not check again how and what is already with the mouse after rebooting this time.
And so thanks for the response (your answer) ..

**Comment by hakuna-m** [comment]
> Regarding EFI / UEFI, I don't remember exactly how I installed Windows at that time, I had an EFI folder on my C: drive. Now this folder does not exist, recently I reinstalled Windows again.
> that is, with this EFI / UEFI I can and will be mistaken.

You can check if Windows is installed in UEFI mode. see [here](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-check-in-windows-if-windows-is-installed-in-uefi-mode-with-secure-boot-)

> I could not check what and how - the black screen was in logon - when entering the user and password in Ubuntu. 

see [askubuntu](https://askubuntu.com/questions/162075/my-computer-boots-to-a-black-screen-what-options-do-i-have-to-fix-it/) or see [our FAQs]( https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-set-boot-options-)

**Comment by somsom37** [comment]
I have an old monitor, probably does not support any frequencies .. So I have not installed it through wubi ubuntu yet.
By the way, according to the above link, I still can't understand what I'm currently loading Windows in EFI or UEFI ..
Thanks for the answers ... Okay, then, maybe I'll do ubuntu again later 
this Issule closed.

**Comment by hakuna-m** [comment]
> I still can't understand what I'm currently loading Windows in EFI or UEFI ..

There is a different Windows mode for [UEFI](https://en.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface) and legacy BIOS only.
