### ISSUE TITLE
wubi20041r342.exe can not run

### ISSUE THREAD

**Issue by sonichy** [hakuna-m/wubiuefi#261]
wubi20041r342.exe can not run, has not information.

**Comment by hakuna-m** [comment]
Run wubi20041r342.exe on [command prompt](https://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/) and see [logs](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-are-the-logs-for-wubiuefi-)

**Comment by sonichy** [comment]
![alt](https://ae01.alicdn.com/kf/Uc0b28874e6ab4da5b3254a0584e57bf5d.jpg)

**Comment by hakuna-m** [comment]
There should be also a log in folder temp.

>  see [logs](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-are-the-logs-for-wubiuefi-)

**Comment by sonichy** [comment]
```
root: Error executing command
>>command=C:\windows\sysnative\bcdedit.exe /enum
>>retval=1
>>stderr=无法打开启动配置数据存储。
```
Found in C:\Windows\System32\bcdedit.exe

**Comment by hakuna-m** [comment]
>`>>stderr=无法打开启动配置数据存储。`

the message in English should be:

`>>stderr=The boot configuration data store could not be opened.`

The boot configuration data store is not the command bcdedit itself. The boot configuration data (BCD) store is usually located in the Boot folder of a hidden partition without an assigned drive letter. You need administrator privileges to access the BCD file with command bcdedit.exe

So first of all, try to run the Command Prompt using a right-click and selecting: ("Run as administrator").

If it also does not work as admin, is there a difference if you run the bcdedit command directly with both paths: 

`C:\windows\sysnative\bcdedit.exe /enum`

and 

`C:\Windows\System32\bcdedit.exe /enum`

?

**Comment by sonichy** [comment]
https://blog.csdn.net/xcntime/article/details/50195349
It seems caused by uefi.
Also cause other boot empty:
![alt](https://img-blog.csdn.net/20151206163147882)
![alt](https://img-blog.csdn.net/20151206163153743)
Copy win8 bcdedit.exe fix failed.
https://www.winpcware.com/extension/exe/bcdedit-exe

**Comment by hakuna-m** [comment]
Sorry, I cannot translate Chinese characters on your screen shots. 

> My mainboard was produced in 2011 year so old has no UEFI, but has linux with grub2.

bcdedit works also on computers with legacy BIOS (non UEFI).

Was there a difference in running bcdedit from different places ?

> `C:\windows\sysnative\bcdedit.exe /enum`
> 
> and
> 
> `C:\Windows\System32\bcdedit.exe /enum`
