### ISSUE TITLE
Can't install another distributions. Missing desktop environments

### ISSUE THREAD

**Issue by nekkan** [hakuna-m/wubiuefi#268]
Hi, I am trying to perform a Pop!_OS installation on my machine, but there are no options other than Ubuntu to select in the desktop environments. The arguments don't seem to solve the problem and don't seem to work properly, in other words, passing a --isopath has no effect and a Ubuntu download starts when I press to perform the installation.

Windows 10 Pro 64-bit 20H2. I'm using the latest version of Wubi.
Used arguments: `D:\Wubi\wubi200420r342.exe --isopath="D:\Wubi\pop-os_20.04_amd64_intel_23.iso" --skipmd5check`

There is no ISO files in the same path as Wubi.

![image](https://user-images.githubusercontent.com/45243386/115762778-31b1b700-a37a-11eb-8118-b872c4989749.png)

**Comment by nekkan** [comment]
I saw that even without any arguments being passed, the only option is still Ubuntu.

**Comment by BruhLua** [comment]
Check the folder where wubiuefi is, if there is ubuntu iso, delete it or put it in other folder
