### ISSUE TITLE
severe Linux crash after Ubuntu Mate have been chosen for installation

### ISSUE THREAD

**Issue by JanuszChmiel** [hakuna-m/wubiuefi#269]
Dear specialist,
You are belonging among programmers elite. Yours approach have even allowed Me to directly boot from USB external harddisk with secure boot enabled by using build in Windows 10 boot manager. I have not been forced to use F12 key. Kernel have been correctly initialised and after several minutes, system has plaied a soft welcome melody. BUt after 10 minutes, system hanged. I had to use hardware turn off button on my laptop. CPu have been very probably overloaded to its 100 % capacity according to fast FAN speed and high temperature of board. Fortunately, EFI driving machine code is capable to receive hardware turn off so I did not had to wait till build in Lion battery have been totally discharged. What do you think, that could happen? It had to be Linux kernel severe crash, because even build in Brltty C binary daemon and UDev could not connect to my USB Braille device. Do you think, that there is AN chance to solve even such complex software issues? 
I Am running 
wubi200420r342.exe
Lenovo Idepad with secure boot enabled.
May be, that installer has wanted to add some non signed Linux kernel module and EFI secure boot block it. Or there is An other problem. My laptop do not contain Wired NEtwork connection, it contain WIFI chip only. 
I Am ready to debug even by using some VIrtual machine for WIndows. Yours  project is wonderful.

**Comment by JanuszChmiel** [comment]
I have found out The cause of this crash. It occur after regular installer restart. Ubuntu kernel also displai severe warnings about fact, that some sectors can not be zeroed some module /dev2 loop BLK.
Very probably installer tried to generate new initramfs and other modules and it can not get successfull.
I will try to use other bootable media than my Toshiba USB harddisk. True is, that before first installer restart, system work perfectly including Orca screen reader support and Braille USB device support. Only kernel warnings about error zweroed some sector and device name /dev2 BLK.

**Comment by JanuszChmiel** [comment]
I have found out The cause of my issue. It is caused by my BIOS. If I finish Ubuntu installation to my external USB harddisk correctly, when I restart Windows 10 which resides on SSD harddisk, BIOS correctly load Kernel and Grub from External USB harddrive. But when Ubuntu installer automatically reboot The system, BIOS refuse to boot from USB external media again and system get stuck. Sad reality is, that it is no more possible to restart WIndows 10 and load kernel correctly like after Wubuntu finish its installation. I Have tried F12 key but I had no success. It is very sad, because somebody very clever have even allowed fully accessible setup with Orca after first reboot to Ubuntu created by Wubi. I AM using 
IdeaPad S540-14IML
laptop.
It is very interesting, which routine Wubi uses because when I choose external USB harddisk, I only restart Windows by using The Wubi option restart and EFI correctly load The kernel I do not have to access boot menu. Very interesting and good practice from you.

**Comment by hakuna-m** [comment]
> I Have tried F12 key but I had no success.

IMHO IdeaPad S540-14IML has a hotkey mode. So sometimes, it is necessary to press Fn + F12 simultaneously..

**Comment by JanuszChmiel** [comment]
Oh, thank you very very much for yours answer. And thank you very much that you are not giving up Wubi development. I wish you, that Canonical Kernel developers will not add some obstructions to The Ubuntu kernel which would cause Wubi project stop to exist.
To be honest, I Am very sad, that Canonical LTD have stopped to release Wubi officially. Advanced programmers or server admins can install Ubuntu on A separate partitions. But why is it impossible to allow Windows users with basic knowledge to try Ubuntu?
Thank you for yours answer. And thank you that you have added Orca screen reader support. It is only necessary to press WINDOWS+ALT+s to run Orca screen reader. User must wait more than 5 Seconds after user hear welcome sound. In other case, at-spi and other processes will not be synchronized correctly, so Orca will speak Ubuntu installer as superuser inaccessible.

I will use my Android phone and Google Lookout assistive technology to read display prompts of BIOS if I will be able to start The system after pressing FN+F12.
When I have tried to install Ubuntu to my primary SDD harddisk, there was An error and after reboot, system did not loaded kernel at all. I will be also cooperating with my sighted and kind mother.
Thank you for yours programmers work.

**Comment by JanuszChmiel** [comment]
I have tried yours latest version of WUBI on my older laptop with UEFI too. It even do not create boot enetries in The Windows 10 boot manager database. No item for booting Ubuntu.
It is veryinteresting.
But as I Am analysing it will be The best to use may be yours oldest WUBI release for 16.01 and use yours .iso for newest one, I will try to experiment. Problem is, that  Windows 10 core is being updated very frequently. I will continue analysing.

**Comment by JanuszChmiel** [comment]
I AM very sorry for this issue. I have found out that yours latest Wubi work ammazingly. I had to only find out how to boot on my new laptop. There is only little issue, that Ubuntu kernel refuses to reboot after installation is finished. WOuld you try to modify ubiquity or other of its opensource part so reboot would not be automatic forced by The installer, so Ubiquity would only end? It is very interesting, because reboot work perfectly after finishing installation. I AM working with Orca screen reader now and system work perfectly. SO I AM very sorry. WUBI creates even MBR code perfectly so EFI system detect loader perfectly. I AM closing this issue and I Am very sorry again.
