### ISSUE TITLE
How do I extend/increase size of my Computer storage in ubuntu?

### ISSUE THREAD

**Issue by DEALWITHIT199** [hakuna-m/wubiuefi#270]
Hi! Question on How to increase my Computer storage? https://prnt.sc/120sow3 Because my free storage left is 16 GB https://imgur.com/a/brbdEHr and I want to increase it, I have an Unallocated space for it. I tried using GParted but the partition/disk is not showing, I also tried GParted in Ubuntu Live and its still not showing. I don't know If I am missing something or I'm just slow to understand. I really need more space for my storage and I appreciate any help. Thank you!

**Comment by nekkan** [comment]
https://help.ubuntu.com/community/ResizeWubiDisk

**Comment by DEALWITHIT199** [comment]
> https://help.ubuntu.com/community/ResizeWubiDisk

How do I know if what /dev/___ is my root directory?

**Comment by nekkan** [comment]
> > https://help.ubuntu.com/community/ResizeWubiDisk
> 
> How do I know if what /dev/___ is my root directory?

In most cases it is /dev/loop0.

**Comment by hakuna-m** [comment]
> How do I know if what /dev/___ is my root directory?

see your second screenshot

> https://imgur.com/a/brbdEHr

device `/dev/loop0` is `/` (=root) directory

BTW, it s also possible to store non system files directly on Windows partition.The Windows partition which contains Wubi disk with Ubuntu is mounted as /host. So you can also use free space without increasing Wubi disk.

**Comment by DEALWITHIT199** [comment]
> https://help.ubuntu.com/community/ResizeWubiDisk

I got an error when running "sudo dd if=/dev/zero bs=1MiB of=/host/ubuntu/disks/root.disk conv=notrunc oflag=append count=2048"
Output: sudo dd if=/dev/zero bs=1MiB of=/host/ubuntu/disks/root.disk conv=notrunc oflag=append count=2048
            dd: error writing '/host/ubuntu/disks/root.disk': No space left on device
            1+0 records in
            0+0 records out
            0 bytes copied, 0.001052 s, 0.0 kB/s
_________________________________________________________________________________________________

And when I run "resize2fs /media/win/ubuntu/disks/root.disk 10G" it says "Please run e2fsck -f /media/win/ubuntu/disks/root.disk first." I run the e2fsck command and run the resize2fs again it repeats says Please run e2fsck first.

**Comment by DEALWITHIT199** [comment]
I finally did it, I manage to increase my root disk, thank you so much nekkan and hakuna-m appreciate the help, my problem is because my Ubuntu disk has no space then I add more space by giving my space from windows disk to ubuntu disk. thank you! its done and hope this might help in the future.
