### ISSUE TITLE
Simply WIFI network configuration

### ISSUE THREAD

**Issue by JanuszChmiel** [hakuna-m/wubiuefi#272]
Linux is not Windows and if there is very positive aspect of Ubiquity installer it is its capability to display available WIFI networks and its ability to allow user to choose one of detected WIFI networks. And user can type password. Ubiquity even automatically store those information in to relevant Ubuntu config files so after reboot, user can be connected to his favourite WIFI. Does somebody of use know, if this routine is only The part of Ubiquity installer, or if installer calls some GTK app for this purpose? I AM working with Ubuntu Mate. May be, that Ubuntu GNome contain also some WIFI configurator as A part of GNome system tray area, applet. I love WUBI because it do not add records to WIndows 10 operating system list on my primary installed harddisk as A result, wake up from hybernate on Windows work perfectly and I AM really working with my external bootable harddrive. I can not use hybernate, only suspended mode, but it is OK, because it is much more faster than hybernation mode and some kernels are having troubles with this feature even if system is installed to real Linux file system.

**Comment by hakuna-m** [comment]
Honestly, we have never changed the WiFi configuration for Wubiuefi. But it is possible to change the existing preseed file for the installer.

If you install with Wubiuefi, you find the preseed file before first reboot from Windows in **ubuntu\install\custom-installation\preseed.cfg** of the target drive.

If you want to create a customized Wubiuefi, you can find the preseed file in https://github.com/hakuna-m/wubiuefi/blob/master/data/preseed.lupin

You can change the lines for wireless configuration manually.
```
d-i netcfg/wireless_essid string essid
d-i netcfg/wireless_wep string
```
see https://help.ubuntu.com/lts/installation-guide/amd64/apbs04.html#preseed-network

Feel free to report your experience with various options.

**Comment by JanuszChmiel** [comment]
Very well done and thank you very much for yours tip.
Fortunately, Ubuntu choice install GNome shell which contain accessible WIFI manager accessed by pressing CTRL+alt+TAB

By The way. .iso image 
Downloaded by using latest stable contain very professional configuration, which allow visually impaired users to use Skype for Linux after using
Snap install skype
Latest stable Ubuntu contain some unpleasant bug, which do not allow to use Skype for Linux again. So Ubuntu Focal used by yours latest stable WUBI is The treasure solution.
I only do not know, how long will be Ubuntu Focal supported.

**Comment by hakuna-m** [comment]
> I only do not know, how long will be Ubuntu Focal supported.

see https://ubuntu.com/about/release-cycle

So if you need long term support, it is still the best solution.

**Comment by JanuszChmiel** [comment]
Thank you. I Am very glad, that this release support Skype so well. Making configurations and finding The cause, whi latest stable Ubuntu do not support Skype is too complex for Me.
Thank you for yours patience, YOu can close The issue.
