### ISSUE TITLE
PeppermintOS 10 fails to install

### ISSUE THREAD

**Issue by PrgmrAtHrt** [hakuna-m/wubiuefi#282]
I am trying to install PeppermintOS 10 with wubiefi. It fails to read the content of the ISO resulting in a dialog box that says "Cannot download the metalink and therefore the ISO". I am using the "Wubi lz" setting which, according to the instructions, should be correct because PeppermintOS 10 has "initrd.lz". 

Additional info:
PeppermintOS 10 is built on Ubuntu 18.04.3.
I am currently using wubiefi 18.04.5 r333.
The log file contains a message "Distro: could not get info None" when it tries to check the ISO.

**Comment by hakuna-m** [comment]
> I am currently using wubiefi 18.04.5 r333.

Probably, you need a newer Wubiuefi revision.  r(elease)333 does not use the latest version to read various distro information. Maybe, [lastest release](https://github.com/hakuna-m/wubiuefi/releases/latest) offers better support, even it is not for Ubuntu 18.04. But special environment like "Wubi lz" does not check the version number. So it is no problem that the version number of PeppermintOS 10 is 10 and not the Ubuntu version number 18.04 or 20.04.

> The log file contains a message "Distro: could not get info None" when it tries to check the ISO.

The important lines are above. e.g.
```
DEBUG  WindowsBackend:   extracting .disk\info from ubuntu-20.04.2.0-desktop-amd64.iso
DEBUG  Distro:   parsing info from str=Ubuntu 20.04.2.0 LTS "Focal Fossa" - Release amd64 (20210209.1)
```

If it works, there is a line like this:

`DEBUG  Distro:   parsed info={'name': 'Ubuntu', 'subversion': 'Release', 'version': '20.04.2.0', 'build': '20210209.1', 'codename': 'Focal Fossa', 'arch': 'amd64'}`

If it fails (in your case), there is a line like this:

`ERROR  Distro: 'NoneType' object has no attribute 'group'`

**Comment by PrgmrAtHrt** [comment]
I tried the latest release. Exact same result.

**Comment by hakuna-m** [comment]
Unfortunately, Peppermint 10 uses not the same pattern for disk info as Ubuntu. If you compare 
`Ubuntu 20.04.2.0 LTS "Focal Fossa" - Release amd64 (20210209.1)`
with
`Peppermint 10 (20191210) - Release amd64`
the build date is on a different place. So pattern in https://github.com/hakuna-m/wubiuefi/blob/master/src/wubi/backends/common/distro.py#L27 does not work.

It is not a huge problem to change the pattern for Peppermint on the weekend. But note, there is no warranty that install will work after fix.

The fix affects only the first layout checks.

**Comment by PrgmrAtHrt** [comment]
I understand. Thank you for investigating this even though it's possible it won't work in the end.

**Comment by hakuna-m** [comment]
The new release should fix the issue: https://github.com/hakuna-m/wubiuefi/releases/tag/200420r343

> DEBUG  Distro:   parsed info={'name': 'Peppermint', 'subversion': 'Release', 'version': '10', 'build': None, 'codename': '20191210', 'arch': 'amd64'}

**Comment by PrgmrAtHrt** [comment]
With the new update, PeppermintOS 10 installs and runs beautifully! Thank you for the update!
