### ISSUE TITLE
Manjaro Linxu/Arch based Linux Distro's support

### ISSUE THREAD

**Issue by AiryPP** [hakuna-m/wubiuefi#283]
Is this possbile? since many people want a USB-Free Option for arch and manjaro etc

**Comment by hakuna-m** [comment]
Theoretically, you can use the Wubi technique also for every Linux distro. But there are no resources to get support for project Wubiuefi.

see also #195

**Comment by AiryPP** [comment]
I think I saw a BAT file that changed the distro link from application.py so it can install arch based distros instead of Debian based

**Comment by AiryPP** [comment]
`REM http://bazaar.launchpad.net/~ubuntu-installer/wubi/trunk/view/head:/src/wubi/application.py#L252
@ECHO OFF
TITLE ArBi - Arch linux Installer For Windows
ECHO Downloading Wubi...
bitsadmin /transfer wubi "https://netcologne.dl.sourceforge.net/project/wubi/Wubi/Wubi-9.04.129/Wubi-9.04-rev129.exe" "%cd%\wubi.exe"
ECHO Enter the URL of Arch linux ISO (Downloadable)
SET /P ArchISOU=} 
bitsadmin /transfer archiso "%ArchISOU%" "%cd%\arch.iso"
ECHO Launching... (NOTE: It dosen't install ubuntu, It's using the arguments to replace ISO and Distro.)
%cd%\wubi.exe --distro Arch --isopath %cd%\arch.iso`

**Comment by hakuna-m** [comment]
If you found a repository with the script, maybe you can ask the owner for help: https://gist.github.com/Lykaksparsz/1a3b742652b4253f7809db0722ef03b8

I don't know the goal of the script. Maybe, it should load an Arch ISO by using the boot loader of Wubi. As far as I know, there are other programs with a similar feature e.g EasyBCD see https://neosmart.net/wiki/easybcd/portable-entries/iso-images/ . 

I don't assume that the script tries to install Arch like Ubuntu with automatic Wubi configuration. IMHO, there are a lot of necessary changes in Wubiuefi to do so. That is the reason, why there is no time to add Arch support in our project, sorry.
