### ISSUE TITLE
Installation of ubuntu stuck on 3/4 of progress

### ISSUE THREAD

**Issue by Jacob1Tm** [hakuna-m/wubiuefi#284]
my ubuntu installation using wubi stuck on 3/4 of installation in installator of ubuntu

**Comment by hakuna-m** [comment]
Please add more details like Wubiuefi log. see https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-are-the-logs-for-wubiuefi-

**Comment by Jacob1Tm** [comment]
[wubi-20.04.2.0-rev342.log](https://github.com/hakuna-m/wubiuefi/files/6911481/wubi-20.04.2.0-rev342.log)

**Comment by Jacob1Tm** [comment]
![image](https://user-images.githubusercontent.com/84023677/127747198-ff23cee4-5374-4132-b68b-ad5300b23378.png)
in wubi its stucks in this moment

**Comment by Jacob1Tm** [comment]
now i use vm to test my iso

**Comment by Jacob1Tm** [comment]
but iso is working i use it in past to other vm

**Comment by Jacob1Tm** [comment]
and in process of install in wubi in installator instalator gives spam of errors

**Comment by Jacob1Tm** [comment]
![20210731_192917.jpg](https://user-images.githubusercontent.com/84023677/127747936-6ca32979-08cc-42e1-b2dd-a964ffcf4a20.jpg)
when instaling this error shows in every seconds

**Comment by hakuna-m** [comment]
> when instaling this error shows in every seconds

Probably, it is a general Ubuntu bug: see https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1521173

The bug description contains a workaround. 

> WORKAROUND: add pci=noaer to your kernel command line:

You can also add `pci=noaer` as boot option: see https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-set-boot-options-

Currently, it is not a boot option of a existing boot menu entry but.....

> Additionally, it is possible to change boot options by pressing <kbd>e</kbd> in the line of the menu entry. After editing you can boot with <kbd>F10</kbd>.

**Comment by Jacob1Tm** [comment]
this error is still there

**Comment by Jacob1Tm** [comment]
thank you after this ubuntu started
