### ISSUE TITLE
voidspace.org.uk is down , cannot build anymore.

### ISSUE THREAD

**Issue by freechelmi** [hakuna-m/wubiuefi#289]
voidspace.org.uk is down , we should host some binairies somewhere to avoid that

**Comment by hakuna-m** [comment]
If voidspace.org.uk is down, you can use a backup. e.g. https://archive.org/web/ provides an internet archive.

So it is possible to change the line in [tools/check_wine](https://github.com/hakuna-m/wubiuefi/blob/master/tools/check_wine#L12) from

`pycrypto_url="http://www.voidspace.org.uk/downloads/pycrypto26/pycrypto-2.6.win32-py2.7.exe"`

to

`pycrypto_url="https://web.archive.org/web/20200502114359/http://www.voidspace.org.uk/downloads/pycrypto26/pycrypto-2.6.win32-py2.7.exe"`

If it is not only a temporary issue, I will change the code, too.

**Comment by freechelmi** [comment]
Thanks , that is perfect !

**Comment by AndrewSav** [comment]
@hakuna-m do you think it's a temporary issue?

**Comment by x-N0** [comment]
????

**Comment by hakuna-m** [comment]
Sorry, I forgot. We will change the link with the next release.

**Comment by freechelmi** [comment]
Fixed in release 345 , thanks !
