### ISSUE TITLE
[Question]I'm getting a error that unicode.pf2 is not found after install and reboot

### ISSUE THREAD

**Issue by AndrewSav** [hakuna-m/wubiuefi#299]
After I run wubiuefi install and it asks for reboot, and I reboot it I'm getting the error like this:

error: file /boot/grub/fonts/unicode.pf2 not found

Then it drops into busybox, any idea what I am doing wrong?

**Comment by hakuna-m** [comment]
Missing GRUB fonts should only cause display issues (e.g.displaying of a Grub menu frame is not correct). So I assume that there is another reason for your busybox issue.

**Comment by AndrewSav** [comment]
It does not seem to display any other errors. Anything I can do to troubleshoot?

**Comment by hakuna-m** [comment]
If you see.....

![](https://raw.githubusercontent.com/wiki/hakuna-m/wubiuefi/images/Install-ESC.png)

.....try to enable verbose mode. see [here](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-set-boot-options-)

BTW busybox itself provides some messages. see e.g. https://github.com/hakuna-m/wubiuefi/issues/29#issuecomment-263599871

**Comment by AndrewSav** [comment]
Thanks, nope, I do not see this, also the is no messages by busybox, how do I proceed? <https://photos.app.goo.gl/JTvSETuB9Czt6JH27>

**Comment by hakuna-m** [comment]
The GRUB boot loader has a graphical issue but it works. But of course, it is difficult to select "verbose mode", if the GRUB boot menu is hidden.
It should be possible to select "verbose mode" from Windows. To do so you can edit the file **C:\ubuntu\install\boot\grub\grub.cfg**

The third line 
`set default=0`
contains the menu entry selected by default.

The first menu entry is zero, the second menu entry is one and so on. So current versions of Wubiuefi should use the pattern from https://github.com/hakuna-m/wubiuefi/blob/master/data/grub.install.cfg which means "verbose mode" is the 7th menu entry. So if you change the line to
 `set default=6`
the new default selection is "verbose mode".

IMHO, that workaround will not be solve your busybox issue but maybe we get more information about the issue.

Additionally, it is also helpful if you can write the affected computer model. Some computer models have known issues with Ubuntu.

**Comment by AndrewSav** [comment]
Thank you.
I have changed that line in my `C:\ubuntu\install\boot\grub\grub.cfg` to be 6, and I also double checked that the 7th entry is "verbose mode" in it. There is no change as to what's shown on screen it is still exactly like in that video linked above.

Here is the model:
![2022-01-02_09-56-20](https://user-images.githubusercontent.com/658865/147860062-a5a61304-95b7-49bf-9982-3454d2e33485.png)

What would be the next step? Many thanks for your assistance!

**Comment by hakuna-m** [comment]
For the graphics issue with Nvidia graphic chip and for additional logs, you can try menu entry "Nvidia graphics workarounds". It should be menu entry no. 5  i.e
`set default=4`

The busybox issue probably depends on the selected drive for Ubuntu. The list contains two identical 8 TB drives. Maybe, it is an unsupported RAID configuration for a Wubi installation ?

**Comment by AndrewSav** [comment]
Hello, thank you for this.

1) Setting `set default=4` makes no difference
2) I do not believe this is NVIDIA, since I used the exact same car with my previous PC with wubiuefi with no problems
3) There is no RAID, the boot drive is NVME

Now I would like to circle back a little, you said:

> Missing GRUB fonts should only cause display issues (e.g.displaying of a Grub menu frame is not correct). So I assume that there is another reason for your busybox issue.

Do you think we should revisit this? If most people do not see this error but I do, it would be logical to conclude, that whatever problem I have may be related to this error. In particular (and excuse me I have no understanding how wubiuefi works, so I'm relaying on you to fill in the blanks).

If I do search on the repo I can see `unicode.pf2` mentioned [here](https://github.com/hakuna-m/wubiuefi/blob/master/data/custom-installation/patch/grub-install-efi#L106). It appears that this script checks if the file is present in `/usr/share/grub` and if so copies it to `/boot/grub/fonts/` after creating this directory.

I'm using the very same standard Ubuntu iso that the installer downloads, it's called `ubuntu-20.04.3-desktop-amd64.iso` I checked that the hash is the same as on the official ubuntu download site. If I mount the .iso image on Windows and then open  `casper\filesystem.squashfs` with 7zip, I can see that `usr/share/grub` directory contains a file `unicode.pf2` which is 2395475 bytes long. So it seems that this error should not happen and yet it does.

Is there anything we can do to get to the root cause. I realise that it could be a red herring, but it is another anomaly that may or may not be related.

**Comment by hakuna-m** [comment]
> Is there anything we can do to get to the root cause.
The output of busybox is visible. So you can try to get information with that tool.

First of all, try to continue to get further error messages with
`exit`

**Comment by hakuna-m** [comment]
> f I do search on the repo I can see `unicode.pf2` mentioned [here](https://github.com/hakuna-m/wubiuefi/blob/master/data/custom-installation/patch/grub-install-efi#L106).

That patch is not needed for the first part of installation. It is installed on **\ubuntu\disks.root.disk** in the second part of installation.

Here
![](https://github.com/hakuna-m/wubiuefi/wiki/images/Install-Restart.png)
and also here 
![](https://github.com/hakuna-m/wubiuefi/wiki/images/Install-ESC.png)
**\ubuntu\disks.root.disk** is empty and has no file system. Usually, it is no problem because the GRUB menu for empty root.disk needs no special fonts.

The second part of installation starts with something like this:
![](https://github.com/hakuna-m/wubiuefi/wiki/images/Install-Ubuntu.png)

That part has a busybox and I assumed in the previous posts that it fails before it can write something to  **\ubuntu\disks.root.disk**

But maybe the second part of installation wrote something to **\ubuntu\disks.root.disk** and the new GRUB menu placed on the disk tries to run the installed Ubuntu.

The installed Ubuntu has also a busybox. 

Nevertheless, IMHO the key to success is to get information from busybox.

Some helpful information from busybox about mounted devices and available partitions is:
```
cat /proc/mounts
cat /proc/partitions
```

A further helpful infomation is the used boot options
`cat /proc/cmdline`

**Comment by AndrewSav** [comment]
Here is what I'm getting for busybox:
![IMG_20220104_090810329](https://user-images.githubusercontent.com/658865/147975602-5b7007c6-2c57-4faa-a74c-8149f147d66b.jpg)
![IMG_20220104_090843918](https://user-images.githubusercontent.com/658865/147975630-6b30dce7-db58-4a41-8919-f22aa4975eb1.jpg)

I never got GUI. After reboot I see the MB BIOS logo and then straight after this the error message `error: file /boot/grub/fonts/unicode.pf2 not found` it hangs there for a second or two, then it looks like a reboot is happening - I have a lighted keyboard it goes dark for a moment and then lights up again. May be not a reboot may be some kind of re-initialisation. Then busy box comes.

The out of the commands you listed are on the first screenshot. What happened after `exit`: `attempted to kill init` is on the second. It looks like busy box is spawn from init as a last ditch because init could not do its job, and when it exits init also exits, which is a panic condition.

Can you tell me if it is possible to mount ` \ubuntu\disks\root.disk` in windows, and if there is any helpful diagnostic info could be gleaned from there? What root.disk format is?

**Comment by hakuna-m** [comment]
The GRUB boot loader installed by Wubiuefi tries to boot an installed Ubuntu. The installed Ubuntu is not on the NVME disk. The Linux name of the partition with Ubuntu is **/dev/sdc2** because that partition has mountpoint **/host**.

I don't know the Windows drive letter but **/dev/sdc** should be the SATA drive with the smallest disk size of your disks.

A possible issue could be that there is a second installation on another drive (e.g a backup) with path ubuntu\disks\root.disk

> Can you tell me if it is possible to mount \ubuntu\disks\root.disk in windows

If you want a new install, **\ubuntu\disks\root.disk** should be empty without a file system. Therefore it is also not possible to mount it.

A **\ubuntu\disks\root.disk** with an installed Ubuntu uses file system ext4. ext4 should be readable with 7zip.

**Comment by hakuna-m** [comment]
If the found Wubi disk is the right one for a new install, the easiest way to erase Wubi disk is to uninstall and install Ubuntu with Wubiuefi and to try it again.
If the found Wubi disk is a second install which should not be erased, you can rename the folder from **ubuntu** to e.g. **ubuntu_old**.
So GRUB boot loader does not find that installed Ubuntu.

**Comment by AndrewSav** [comment]
Thank you, that was awesome!!! I renamed the old one from ubuntu to ubuntu old, got "completing the ubuntu installation" and then the installation UI. After it finished though it hanged with `[    0.719978] igc 0000:6e:00.0 no suspend buffer for PTN`. Ctrl-Alt-F2 through to F6 switched to black screen with cursor only Ctrl-Alt-F1 goes back to this message. I tried Ctrl-C, Ctrl-Z and Ctrl-Alt-Del to no avail.

When I hard restart the computer it booted to windows, there was no prompt to chose which OS to boot.

![IMG_20220104_234703780](https://user-images.githubusercontent.com/658865/148049025-79d9e6fe-782f-4b0c-86d0-81812fbea4c6.jpg)

**Comment by AndrewSav** [comment]
Actually I think this is more or less solved now, I'm going to close this soon. The error message [seems to be benign](https://lore.kernel.org/lkml/20210920163926.101528761@linuxfoundation.org/), what actually happen is that for some reason when ubuntu tries to reboot it hangs instead. After that if I go to BIOS there is an ubuntu entry there, and choosing it boots ubuntu.

I have one last questions though. Previously, after using wubiuefi upon boot I saw _windows boot manager_ with two options: windows and ubuntu. Now as described above I see grub which offers either ubuntu on WBM which boots windows. Why the difference? Is it possible for me to have WBM not grub for that selection?

Once again my sincere gratitude for help!

**Comment by AndrewSav** [comment]
Actually that question is [FAQ](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-is-my-ubuntu-entry-in-windows-boot-manager-for-uefi-). Okay, I think we are done here, once again thank you for your help. Do you accept donations?

**Comment by hakuna-m** [comment]
> Do you accept donations @hakuna-m?

Feel free to use emoticons for your reaction or a star for the repo. But help and support should not depend on donations.
