### ISSUE TITLE
EFI error when run wubi1604r303

### ISSUE THREAD

**Issue by nhymxu** [hakuna-m/wubiuefi#3]
Hi,

I'm trying to use wubi1604r303 with kubuntu 16.04.
After setup, I got error

> 04-03 19:47 DEBUG  TaskList: ## Finished choose_disk_sizes
> 04-03 19:47 DEBUG  TaskList: ## Running create_preseed...
> 04-03 19:47 DEBUG  TaskList: ## Finished create_preseed
> 04-03 19:47 DEBUG  TaskList: ## Running modify_bootloader...
> 04-03 19:47 DEBUG  TaskList: New task modify_bcd
> 04-03 19:47 DEBUG  TaskList: ### Running modify_bcd...
> 04-03 19:47 DEBUG  WindowsBackend: modify_bcd Drive(C: hd 59739.8125 mb free ntfs)
> 04-03 19:47 DEBUG  WindowsBackend: EFI boot
> 04-03 19:47 ERROR  TaskList: substring not found
> Traceback (most recent call last):
>   File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
>   File "\lib\wubi\backends\win32\backend.py", line 805, in modify_bcd
>   File "\lib\wubi\backends\win32\backend.py", line 577, in modify_EFI_folder
> ValueError: substring not found
> 04-03 19:47 DEBUG  TaskList: # Cancelling tasklist
> 04-03 19:47 DEBUG  TaskList: New task modify_bcd
> 04-03 19:47 ERROR  root: substring not found
> Traceback (most recent call last):
>   File "\lib\wubi\application.py", line 58, in run
>   File "\lib\wubi\application.py", line 132, in select_task
>   File "\lib\wubi\application.py", line 158, in run_installer
>   File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
>   File "\lib\wubi\backends\win32\backend.py", line 805, in modify_bcd
>   File "\lib\wubi\backends\win32\backend.py", line 577, in modify_EFI_folder
> ValueError: substring not found
> 04-03 19:47 DEBUG  TaskList: New task modify_bcd
> 04-03 19:47 DEBUG  TaskList: ## Finished modify_bootloader
> 04-03 19:47 DEBUG  TaskList: # Finished tasklist

I'm using Dell vostro 5560 with ssd 120GB for windows ( efi partition here )
and HDD 1TB for install wubi folder here.
HDD not have efi partition.

thanks you!

**Comment by nhymxu** [comment]
result for bcdedit /enum {bootmgr}

not found **partition=** string

![bcdedit](https://cloud.githubusercontent.com/assets/535617/14232590/8c9be348-f9d9-11e5-8d5c-d6553bce0f9a.jpg)

**Comment by hakuna-m** [comment]
Wubi assumes that the BCD entry for the EFI "Windows Boot Manager" always contains 
`device                  partition=`
In your case the entry is
`device                  unknown`
Is it possible to mount EFI partition with the following Windows command:
`mountvol s: /s`
After that EFI partition should set as Windows drive **s:**. 

If it is possible, I will change the program.

**Comment by nhymxu** [comment]
@hakuna-m I'm trying open cmd (as admin)
type 
``
mountvol s: /s
``

open with **ithurricanept powertools** and can see partition data

try again with 
``
bcdedit /enum {bootmgr}
``

still device unknow

I'm using Windows 10 x64
![untitled](https://cloud.githubusercontent.com/assets/535617/14233089/8b95c69e-f9e8-11e5-847e-cc39ab04cdad.jpg)

**Comment by hakuna-m** [comment]
No problem. If "Windows Boot Manager" boots from an unknown device, Ubuntu boot loader should also boot from an unknown device. I will change only the command that expects a known partition.

**Comment by nhymxu** [comment]
Thanks you :smile:

**Comment by hakuna-m** [comment]
The change has a drawback. After changing, in your case Wubi doesn't work if your EFI partition is already mounted. IMHO it is better, if you set the EFI partition for your Windows as [the documentation of Microsoft](https://technet.microsoft.com/en-us/library/dn336950.aspx) says.

In your case, you can use on Windows command prompt as admin:
```
mountvol s: /s
bcdedit /set {bootmgr} device partition=s:
```
After that, your device entry should be changed from **unknown** to **partition=s:**

If you unmount your partition with
`mountvol s: /d`

the device entry should be changed from **partition=s:** to a Windows disk/partition name/number, something like `partition=\Device\Harddisk\Volume1`

**Comment by hakuna-m** [comment]
Nevertheless, I should fix the issue by changing Wubi if the error occurs on a lot of systems.

**Comment by hakuna-m** [comment]
I changed the program ...
```
--- a/src/wubi/backends/win32/backend.py
+++ b/src/wubi/backends/win32/backend.py
@@ -574,7 +574,10 @@ class WindowsBackend(Backend):
     def modify_EFI_folder(self, associated_task,bcdedit):
         command = [bcdedit, '/enum', '{bootmgr}']
         boot_drive = run_command(command)
-        boot_drive = boot_drive[boot_drive.index('partition=')+10:]
+        if 'partition=' in boot_drive:
+            boot_drive = boot_drive[boot_drive.index('partition=')+10:]
+        else:
+            boot_drive = boot_drive[boot_drive.index('device')+24:]
         boot_drive = boot_drive[:boot_drive.index('\r')]
         log.debug("EFI boot partition %s" % boot_drive)
         # if EFI boot partition is mounted we use it
```
... and I built a new wubi.exe.  I uploaded it [here](https://www.dropbox.com/sh/6uqomp8l1frcd1y/AACC3UyJjId3gkw6EiRZ6lGTa/wubitest.exe?dl=0) for temporary use. (wubitest.exe md5sum: c3a7c21c7c488d80943a9cd8491f7266). If it works for you, I will release the new version as revision 304.

**Comment by nhymxu** [comment]
![untitled](https://cloud.githubusercontent.com/assets/535617/14262308/05c85b56-fadf-11e5-86c9-48e144785438.jpg)


```
04-05 03:26 DEBUG  TaskList: ## Finished choose_disk_sizes
04-05 03:26 DEBUG  TaskList: ## Running create_preseed...
04-05 03:26 DEBUG  TaskList: ## Finished create_preseed
04-05 03:26 DEBUG  TaskList: ## Running modify_bootloader...
04-05 03:26 DEBUG  TaskList: New task modify_bcd
04-05 03:26 DEBUG  TaskList: ### Running modify_bcd...
04-05 03:26 DEBUG  WindowsBackend: modify_bcd Drive(C: hd 59722.2851563 mb free ntfs)
04-05 03:26 DEBUG  WindowsBackend: EFI boot
04-05 03:26 DEBUG  WindowsBackend: EFI boot partition unknown
04-05 03:26 DEBUG  WindowsBackend: Temporary EFI drive H:
04-05 03:26 DEBUG  WindowsBackend: Copying EFI folder D:\C\nhymxuTemp\pylF65B.tmp\winboot\EFI -> H:\EFI\ubuntu\wubildr
04-05 03:26 DEBUG  WindowsBackend: efi_arch=x64
04-05 03:26 ERROR  TaskList: Error executing command
>>command=C:\Windows\sysnative\bcdedit.exe /set {fwbootmgr} bootsequence {8ee7a0fc-faa3-11e5-846c-e0db55edfbb2}
>>retval=1
>>stderr=Element not found.


>>stdout=
Traceback (most recent call last):
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\win32\backend.py", line 816, in modify_bcd
  File "\lib\wubi\backends\common\utils.py", line 66, in run_command
Exception: Error executing command
>>command=C:\Windows\sysnative\bcdedit.exe /set {fwbootmgr} bootsequence {8ee7a0fc-faa3-11e5-846c-e0db55edfbb2}
>>retval=1
>>stderr=Element not found.


>>stdout=
04-05 03:26 DEBUG  TaskList: # Cancelling tasklist
04-05 03:26 DEBUG  TaskList: New task modify_bcd
04-05 03:26 ERROR  root: Error executing command
>>command=C:\Windows\sysnative\bcdedit.exe /set {fwbootmgr} bootsequence {8ee7a0fc-faa3-11e5-846c-e0db55edfbb2}
>>retval=1
>>stderr=Element not found.


>>stdout=
Traceback (most recent call last):
  File "\lib\wubi\application.py", line 58, in run
  File "\lib\wubi\application.py", line 132, in select_task
  File "\lib\wubi\application.py", line 158, in run_installer
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\win32\backend.py", line 816, in modify_bcd
  File "\lib\wubi\backends\common\utils.py", line 66, in run_command
Exception: Error executing command
>>command=C:\Windows\sysnative\bcdedit.exe /set {fwbootmgr} bootsequence {8ee7a0fc-faa3-11e5-846c-e0db55edfbb2}
>>retval=1
>>stderr=Element not found.


>>stdout=
04-05 03:26 DEBUG  TaskList: New task modify_bcd
04-05 03:26 DEBUG  TaskList: ## Finished modify_bootloader
04-05 03:26 DEBUG  TaskList: # Finished tasklist
```

**Comment by hakuna-m** [comment]
> `bcdedit.exe /set {fwbootmgr} bootsequence {8ee7a0fc-faa3-11e5-846c-e0db55edfbb2}`
The command should define the one-time boot sequence for the EFI firmware. Ubuntu should be loaded first but for one time only

I will change the program and skip that command if an error occurs.

**Comment by nhymxu** [comment]
I see mount EFI partition and copy ubuntu folder work well.

ubuntu folder found in /EFI/ubuntu

**Comment by hakuna-m** [comment]
I added a second patch:
```
--- a/src/wubi/backends/win32/backend.py
+++ b/src/wubi/backends/win32/backend.py
@@ -808,9 +811,12 @@ class WindowsBackend(Backend):
             id = run_command(command)
             id = id[id.index('{'):id.index('}')+1]
             run_command([bcdedit, '/set', id, 'path', efi_path])
-            run_command([bcdedit, '/set', '{fwbootmgr}', 'displayorder', id, '/addlast'])
-            run_command([bcdedit, '/set', '{fwbootmgr}', 'timeout', '10'])
-            run_command([bcdedit, '/set', '{fwbootmgr}', 'bootsequence', id])
+            try:
+                run_command([bcdedit, '/set', '{fwbootmgr}', 'displayorder', id, '/addlast'])
+                run_command([bcdedit, '/set', '{fwbootmgr}', 'timeout', '10'])
+                run_command([bcdedit, '/set', '{fwbootmgr}', 'bootsequence', id])
+            except Exception, err: #this shouldn't be fatal
+                log.error(err)
             registry.set_value(
                 'HKEY_LOCAL_MACHINE',
                 self.info.registry_key,
```
If an error occurs because of the last three bcdedit EFI commands (displayorder, timeout and bootsequence), it is not fatal and Wubi skips these commands. This means for you that probably, you have to select Ubuntu from your EFI menu manually at first boot, too. But it should work.

I uploaded the new version [here](https://www.dropbox.com/sh/6uqomp8l1frcd1y/AACC3UyJjId3gkw6EiRZ6lGTa/wubitest.exe?dl=0) (wubitest.exe md5sum: 2ec8cb7cdc6249756a6f67f83bb75634)

**Comment by nhymxu** [comment]
@hakuna-m work great on windows side.
After reboot - run ubuntu-gnome install progress.
I get error when system try install grub

The "grub-efi-amd64" package failed to install into /target/. Without the Grub boot loader, the installed system will not found.

Thanks you!

**Comment by hakuna-m** [comment]
Wubi installs Grub2 boot loader from Windows side. Probably, it is possible to boot into Ubuntu GNOME despite your error message.

> `The "grub-efi-amd64" package failed to install into /target/. Without the Grub boot loader, the installed system will not found.`

So my question are: is it possible to boot into Ubuntu GNOME from EFI menu ?
If it is possible: is your EFI partion mounted on /boot/efi ?

Wubi installs a GRUB patch for EFI systems but only if path /boot/efi exists on target [see](https://github.com/hakuna-m/wubiuefi/blob/master/data/custom-installation/hooks/post-installer.sh#L11)
`        if [ -d /target/boot/efi ]; then`

If the GRUB patch is also needed on some tricky installations without mounted EFI partition, I will change that line.

**Comment by nhymxu** [comment]
After run wubi setup guild. I restart my computer, press F12 to go boot choose menu. Choose ubuntu from this menu.

Boot to Ubuntu Gnome install screen. Everything work till this error dialog appear. Install abort.

**Comment by hakuna-m** [comment]
> Install abort.
If you reboot after that, press F12 again, select Ubuntu from EFI menu, does Ubuntu boot ?

GRUB installation is one of the latest parts of the installation. So in some cases it is not necessary to install a running system.

Nevertheless, IMHO it makes sense to change the EFI patch:
```
--- a/data/custom-installation/hooks/post-installer.sh
+++ b/data/custom-installation/hooks/post-installer.sh
@@ -8,7 +8,7 @@ if [ -f /custom-installation/patch/loop-remount ]; then
 fi
 
 if [ -f /custom-installation/patch/grub-install ] && [ -f /custom-installation/
-        if [ -d /target/boot/efi ]; then
+        if [ -d /sys/firmware/efi ]; then
                mkdir -p /target/usr/local/sbin
                cp /custom-installation/patch/grub-install /target/usr/local/sbi
                chmod +x /target/usr/local/sbin/grub-install
```

**Comment by hakuna-m** [comment]
I built a new version and uploaded it [here](https://www.dropbox.com/sh/6uqomp8l1frcd1y/AACC3UyJjId3gkw6EiRZ6lGTa/wubitest.exe?dl=0) again. md5sum: 6eb1a039c75166dc2a23581f1d3ed722

The new version should install the GRUB EFI patch on EFI systems even if no EFI partition is mounted.

**Comment by nhymxu** [comment]
No, After reselect ubuntu from EFI menu, laptop auto reboot and boot to windows ( default )

**Comment by nhymxu** [comment]
After all, eveything work very good.

Thanks you @hakuna-m
