### ISSUE TITLE
"blk_update_request: I/O error, dev loop0, sector 0 op 0x1:(WRITE) flags 0x800 phys_seg 0 prio class 0" error after trying to install Kubuntu 21.10 using Wubi 20.04.3

### ISSUE THREAD

**Issue by dashwr** [hakuna-m/wubiuefi#304]
Tried running the latest Kubuntu iso on Wubi thinking it might work; it got through the install process (both Wubi's and Kubuntu's) smoothly and with no apparent errors but every time it finishes the installation i'm met with a black screen repeating that same line over and over again. Rebooting and forcing shimx64.efi to run before Windows just brings me to the MOK error screen, even when I've already assigned it a MOK.
May be a stupid thing to ask considering the newest versions might not be 100% supported as of now, but is there possibly a fix for it?

Btw, kudos to you for making such an amazing program! i don't currently have a usb drive so im relying on it a bit to get Linux running.

**Comment by hakuna-m** [comment]
> but every time it finishes the installation i'm met with a black screen repeating that same line over and over again.

That sounds like two known issues:

- automatic reboot after installation does not work. see https://github.com/hakuna-m/wubiuefi/issues/193#issuecomment-619521260
- blk_update messages see https://github.com/hakuna-m/wubiuefi/issues/16#issuecomment-237565006

But both issues are often harmless and don't end in MOK error screen. 

> Rebooting and forcing shimx64.efi to run before Windows just brings me to the MOK error screen, even when I've already assigned it a MOK.

The GRUB boot loader should work with the builtin MOK (hakunamatata_wubi.cer) . It is also used to boot into Linux part of installation. But it is possible that you need special kernel modules e.g. for graphics. Those modules are signed with a personal key created during installation. 

The easiest workaround for MOK errors is to disable Secure Boot in UEFI BIOS. see [here](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-change-uefi-firmware-settings-from-windows-)

**Comment by dashwr** [comment]
> > but every time it finishes the installation i'm met with a black screen repeating that same line over and over again.
> 
> That sounds like two known issues:
> 
> - automatic reboot after installation does not work. see https://github.com/hakuna-m/wubiuefi/issues/193#issuecomment-619521260
> - blk_update messages see https://github.com/hakuna-m/wubiuefi/issues/16#issuecomment-237565006
> 
> But both issues are often harmless and don't end in MOK error screen. 
> 
> > Rebooting and forcing shimx64.efi to run before Windows just brings me to the MOK error screen, even when I've already assigned it a MOK.
> 
> The GRUB boot loader should work with the builtin MOK (hakunamatata_wubi.cer) . It is also used to boot into Linux part of installation. But it is possible that you need special kernel modules e.g. for graphics. Those modules are signed with a personal key created during installation. 
> 
> The easiest workaround for MOK errors is to disable Secure Boot in UEFI BIOS. see [here](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-change-uefi-firmware-settings-from-windows-)

Tried it again, it just kept booting into the installer every time i used easyUEFI to boot into shimx64.efi after the black error screen (kind of a loop). It only asked for the MOK once this time around, though. 

To be clear - it did automatically reboot into the Kubuntu installer after Wubi was done, the black screen error happens after the Kubuntu installer finishes. Sorry if i wasn't clear enough.

Also, it never asked me for a key or anything, it just prints that error over and over again once it reaches "[ OK ] Starting Shuts down the "live" preinstalled system cleanly..." when automatically rebooting after Kubuntu's done installing.

**Comment by dashwr** [comment]
Huh. I rebooted after the installer and the errors, chose "Continue boot" instead of enrolling a MOK and it booted into Kubuntu just fine.
Odd, but at least it worked!
