### ISSUE TITLE
Cannot download the metalink and therefore the ISO

### ISSUE THREAD

**Issue by Assault1892** [hakuna-m/wubiuefi#306]
I tried to install Ubuntu Budgie on Wubiuefi rev344 and was interrupted with a "Cannot download the metalink and therefore the ISO" error.
The list file I am trying to download is for 20.04 and has already been deleted from the server.

Here is the log file: https://pastebin.com/8aE123Cb

**Comment by hakuna-m** [comment]
> I tried to install Ubuntu Budgie on Wubiuefi rev344 and was interrupted with a "Cannot download the metalink and therefore the ISO" error.

The purpose of [2004r344](https://github.com/hakuna-m/wubiuefi/releases/tag/2004r344) is to add support for more Ubuntu based distros without automatic downloads. There has never been the intention to improve download support of [20043r343](https://github.com/hakuna-m/wubiuefi/releases/tag/20043r343).

Either you download ISO manually (https://cdimage.ubuntu.com/ubuntu-budgie/releases/20.04.3/release/ubuntu-budgie-20.04.4-desktop-amd64.iso) or you wait for [20044r344](https://github.com/hakuna-m/wubiuefi/releases/tag/20044r344) which will be released soon.

**Comment by hakuna-m** [comment]
[20044r344](https://github.com/hakuna-m/wubiuefi/releases/tag/20044r344) has been released.

**Comment by Assault1892** [comment]
thanks!
