### ISSUE TITLE
Always stuck at asus logo

### ISSUE THREAD

**Issue by RichardLuo0** [hakuna-m/wubiuefi#325]
After pressing the power button, the computer always stops at ASUS logo. The only way is to press ESC and manually choose Ubuntu or Windows. Is it supposed to be like this? How to boot windows by default?
I remember when I installed ubuntu in a separate drive, I can change the bios settings to boot ubuntu or windows by default. Can I restore the behaviour with wubiuefi?

**Comment by hakuna-m** [comment]
> Is it supposed to be like this?

It is not supposed but it depends on UEFI BIOS settings. 

Wubiuefi tries to set UEFI menu with Windows program bcdedit (needs admin privileges).

Check your UEFI menu entries with
`bcdedit /enum firmware`

e.g. https://github.com/hakuna-m/wubiuefi/issues/15#issuecomment-236347022

identifier {fwbootmgr} contains the order of your UEFI menu boot entries (displayorder).

If you want to boot Windows by default, {bootmgr} should be the first entry.
If you want to boot Wubiuefi by default, identifier which contains path \EFI\ubuntu\wubildr\shimx64.efi should be the first entry.

You can change it by using:
`bcdedit /set {fwbootmgr} displayorder {guid} /addfirst`

Replace {guid} with the identifier which should be booted on default. e.g. {bootmgr} or identifiers like {cbfe2a65-d996-11e5-8118-8b921f5b8924}

Another possibility is to use Windows programs like EasyUEFI to change bootorder or sometimes UEFI BIOS also provides tools to change default boot order. [How can I change UEFI firmware settings from Windows ?](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-change-uefi-firmware-settings-from-windows-)

**Comment by RichardLuo0** [comment]
Thank you. I simply set all timeouts to 0 with `bcdedit /set "{fwbootmgr}" timeout 0` and the problem was solved
