### ISSUE TITLE
Laptop: Installation OK,  Bootloader shows "Kunbuntu" but then I get Windows only

### ISSUE THREAD

**Issue by github-klaus** [hakuna-m/wubiuefi#339]
I have used on a Lenovo-Laptop Wubi for Ubuntu 22.04.2 (rev. 345).
Installation works fine (almost 2 days for Kubuntu-torrent!). After restart and "F12" during booting I could choose a boot device: I choose "Kubuntu", but I get Windows (exact the same as choosing "Windows Boot Manager")!
I appreciate any help to boot Kubuntu!

Thank you very much!
Klaus
![DSC_0002_resized](https://github.com/hakuna-m/wubiuefi/assets/141876415/dcff616a-7dc1-4ede-8023-7d1dff920fe2)
![DSC_0013_resized](https://github.com/hakuna-m/wubiuefi/assets/141876415/cd1d00bc-30b6-46a1-bf6a-fff7e8c313aa)
![DSC_0015_resized](https://github.com/hakuna-m/wubiuefi/assets/141876415/19b284a8-8c60-4cae-85d1-3e0a602b6437)

**Comment by hakuna-m** [comment]
Wubi(uefi) uses Windows command bcdedit to change menu entries.

So it is necessary to analyze the view of your menu entries with bcdedit.

1. Start command prompt as administrator with e.g the following method: 

- Use Windows + R Keyboard Shortcut  
- Type “cmd“
- Press Ctrl + Shift and hit Enter key.

2. Type `bcdedit /enum firmware

3. The output should be something like that: https://github.com/hakuna-m/wubiuefi/issues/15#issuecomment-236347022

4. In your case, the path of the menu entry for "Kubuntu" is important.

```
Windows Boot Manager
--------------------
identifier              {cbfe2a65-d996-11e5-8118-8b921f5b8924}
device                  partition=\Device\HarddiskVolume4
path                    \EFI\ubuntu\wubildr\shimx64.efi
description             Kubuntu
locale                  en-US
inherit                 {globalsettings}
default                 {current}
resumeobject            {cbfe2a61-d996-11e5-8118-8b921f5b8924}
displayorder            {current}
toolsdisplayorder       {memdiag}
timeout                 30
```

It should be **\EFI\ubuntu\wubildr\shimx64.efi**.

**Comment by github-klaus** [comment]
Thank you a lot for your fast and detailed answer!
Following your advice I get following output:


C:\Users\Administrator>bcdedit /enum firmware

Start-Manager für Firmware
--------------------------
Bezeichner              {fwbootmgr}
displayorder            {bootmgr}
                        {ae920fee-020c-11ec-83cb-c03809372681}
                        {ae920fe8-020c-11ec-83cb-c03809372681}
                        {ae920fe9-020c-11ec-83cb-c03809372681}
                        {ae920fea-020c-11ec-83cb-c03809372681}
                        {ae920fed-020c-11ec-83cb-c03809372681}
                        {ae920ff4-020c-11ec-83cb-c03809372681}
timeout                 10

Windows-Start-Manager
---------------------
Bezeichner              {bootmgr}
device                  partition=\Device\HarddiskVolume1
path                    \EFI\Microsoft\Boot\bootmgfw.efi
description             Windows Boot Manager
locale                  de-DE
inherit                 {globalsettings}
default                 {current}
resumeobject            {ae920ff0-020c-11ec-83cb-c03809372681}
displayorder            {current}
toolsdisplayorder       {memdiag}
timeout                 30

Windows-Start-Manager
---------------------
Bezeichner              {ae920ff4-020c-11ec-83cb-c03809372681}
device                  partition=\Device\HarddiskVolume1
path                    \EFI\ubuntu\wubildr\shimx64.efi
description             Kubuntu
locale                  de-DE
inherit                 {globalsettings}
default                 {current}
resumeobject            {ae920ff0-020c-11ec-83cb-c03809372681}
displayorder            {current}
toolsdisplayorder       {memdiag}
timeout                 30

...


So there is after "path" "\EFI\ubuntu\wubildr\shimx64.efi"!
Do you have another idea what could be wrong?

Thank you in advance!
Klaus

**Comment by jdev082** [comment]
Does the boot menu show before Windows attempts to boot? Restart your computer through Windows. Hold shift before clicking restart. I'm not exactly sure where the option to boot a different system from the Windows boot menu is. But when you find it, click it. The entry might be called Kubuntu or Ubuntu.

**Comment by github-klaus** [comment]
Holding shift during clicking restart results in a screen with four options: I choose "Fortsetzen"
Test 1: doing nothing during restart: I get Windows
Test 2: "F12" during restart: "Please select boot device" - I select "Kubuntu", but I get Windows (exact the same as choosing "Windows Boot Manager")!

![DSC_0020_resized](https://github.com/hakuna-m/wubiuefi/assets/141876415/a0c349b8-f94f-46ab-a220-c159964d1b8e)

Any idea how I can start Kubuntu? - Thank you!

**Comment by hakuna-m** [comment]
Probably, it is necessary to disable Secure Boot because of a new "security" feature of some Lenovo laptops: https://mjg59.dreamwidth.org/59931.html

[Check for Secure Boot](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-check-in-windows-if-windows-is-installed-in-uefi-mode-with-secure-boot-)
[Disable Secure Boot](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#how-can-i-change-uefi-firmware-settings-from-windows-)

Also in [German](https://github.com/hakuna-m/wubiuefi/wiki/FAQ_de#wie-kann-ich-%C3%BCberpr%C3%BCfen-ob-windows-im-uefi-modus-mit-secure-boot-installiert-wurde-) available.

**Comment by github-klaus** [comment]
Thank you a lot for your fast and detailed answer!


Following your guide (1):

How can I check in Windows if Windows is installed in UEFI mode with Secure Boot ?
- Press Windows + R
- Type msinfo32
- Look for entry | BIOS Mode | UEFI |
- If BIOS mode is UEFI look also for | Secure Boot State | On |

Result: Secure Boot is enabled!


Following your guide (2):

How can I change UEFI firmware settings from Windows ?
- Find Shut down / Restart menu
- Press Shift + click on Restart
- After restart click on Troubleshoot -> Advanced options -> UEFI Firmware Settings -> Restart

Result: System Password:
                System Password:
I have the administration password for windows, only :-(
Therefore, I can't proceed :-(


Conclusion: Don't see any chance to succeed and therefore I give up. Thank you for your help - and keep up your highly appreciated work!
