### ISSUE TITLE
Kubuntu 23.10 update-grub fatal error

### ISSUE THREAD

**Issue by rounk-ctrl** [hakuna-m/wubiuefi#341]
![image](https://github.com/hakuna-m/wubiuefi/assets/70931017/74d69473-fad0-4012-b528-6bcccbef218b)

wubi 345

**Comment by hakuna-m** [comment]
Probably, same issue as described in #342

**Comment by rounk-ctrl** [comment]
yep i noticed that while upgrading to 23.10

**Comment by hakuna-m** [comment]
I will change [10_lupin](https://github.com/hakuna-m/wubiuefi/blob/master/data/custom-installation/patch/10_lupin) with next release to avoid issues with new versions.
