### ISSUE TITLE
https://github.com/hakuna-m/wubiuefi/issues/310#

### ISSUE THREAD

**Issue by AlddanyYSzon** [hakuna-m/wubiuefi#343]

**Comment by AlddanyYSzon** [comment]
> _No description provided._
`[null](url)`

**Comment by AlddanyYSzon** [comment]
https://docs.github.com/articles/github-community-guidelines

**Comment by AlddanyYSzon** [comment]
https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disruptive-comments

**Comment by AlddanyYSzon** [comment]
https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disruptive-comments

**Comment by AlddanyYSzon** [comment]
Edit close https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disruptive-comments

**Comment by AlddanyYSzon** [comment]
https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disr

**Comment by hakuna-m** [comment]
Is it a testing issue which I can delete ?
