### ISSUE TITLE
Debian Stretch support?

### ISSUE THREAD

**Issue by wean-irdeh** [hakuna-m/wubiuefi#40]
Can this be used in Debian Stretch? Since Ubuntu is a Debian fork.

**Comment by hakuna-m** [comment]
Wubi and Wubiuefi uses a preseed file for [automating Ubiquity](https://wiki.ubuntu.com/UbiquityAutomation). If an ISO doesn't contain [Ubiquity](https://wiki.ubuntu.com/Ubiquity), an automatic install with Wubi method doesn't work.

So IMHO, it doesn't work for Debian Stretch, if you don't change Wubi or the Debian Stretch ISO.
