### ISSUE TITLE
How does lupin works?

### ISSUE THREAD

**Issue by wean-irdeh** [hakuna-m/wubiuefi#41]
Which files responsible for the loopback booting?  An initramfs script which has named lupin seems to be responsible for first time use only

**Comment by hakuna-m** [comment]
The additional files for loopback booting - comparing them with other Ubuntu installations - are within package [lupin-support](http://packages.ubuntu.com/lupin-support).

Additionally, Wubiuefi has a fix for an [initramfs issue](https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/1317437) ( [loop-remount](https://github.com/hakuna-m/wubiuefi/blob/master/data/custom-installation/patch/loop-remount) ) and a fix that command `grub-install` also works for EFI ( [grub-install-efi](https://github.com/hakuna-m/wubiuefi/blob/master/data/custom-installation/patch/grub-install-efi) ).

**Comment by wean-irdeh** [comment]
How do you manage to get losetup terminated on shutdown after the root filesystem unmounted cleanly? Using manual method, I always get a lot of error because losetup terminated earlier at shutdown which causes root filesystem unmounted cleanly and init scripts can't run successfully

**Comment by hakuna-m** [comment]
> How do you manage to get losetup terminated on shutdown after the root filesystem unmounted cleanly?

Fortunately, there has never been the need for me to manage this problem.

IMHO it is managed by standard Ubuntu initramfs-tools packages by using 
`mount -o move`
see [here](http://unix.stackexchange.com/a/61157) and [here](https://git.launchpad.net/~cyphermox/initramfs-tools/+git/update/tree/scripts/local?h=ubuntu)

**Comment by NyaMisty** [comment]
Sorry to bother in such an old post.
@hakuna-m  Could you please explain why the `mount -o move` can solve the issue?
