### ISSUE TITLE
Cannot uninstall wubiuefi on system without hibernate (powercfg /h off error)

### ISSUE THREAD

**Issue by wean-irdeh** [hakuna-m/wubiuefi#43]
My system doesn't support hibernate because I boot from VHD, but it shouldn't stopped me from uninstall wubiuefi.

**Comment by hakuna-m** [comment]
You are right. Wubiuefi should only enable hibernation during uninstall if it has been disabled during installation. In your case, it has never been enabled.

I will change this for future releases.

**Comment by hakuna-m** [comment]
Finally, I added an error handling for both powercfg commands (during install and uninstall). There is still no query whether powercfg is needed but there should be no fatal error.

**Comment by wean-irdeh** [comment]
Using wubi10704r321 and issues still persist

![wrong](https://cloud.githubusercontent.com/assets/26435462/24923549/13d0451c-1f1c-11e7-9653-2bae898da322.png)

**Comment by hakuna-m** [comment]
If you install a new version, it runs the uninstaller of the installed version (rev319). Therefore the log file is still wubi-16.04.2-**rev319**.log. Either replace the file **uninstall-wubi.exe** within folder ubuntu with the new Wubi version (the file **uninstall-wubi.exe** is identical with the wubi.exe which you used for installation) or remove the Wubi installed Ubuntu manually before installing a new version.

**Comment by wean-irdeh** [comment]
I have to delete the folder manually but at least the issue fixed now! Thank you
