### ISSUE TITLE
Dell Laptop RAID mode

### ISSUE THREAD

**Issue by clarencechien** [hakuna-m/wubiuefi#44]
Try r319 on Dell Latitude 7270 (win10/nvme/raid mode/UEFI/secure boot)
Can't boot into ubuntu, initramfs prompt and error message: "Could not find the iso /ubuntu/installer/installation.iso"

attempt:
1. switch RAID to ACHI 
2. switch UEFI to legacy 

option 1 or 2, it's fine to finish installation, but affect win10 boot

About this intel's fake RAID mode, could I just copy installation.iso into root.disk and delete it after installation? Or should I need RAID driver/something else?

**Comment by hakuna-m** [comment]
In general, Wubiuefi has no special RAID driver. It is always necessary that standard Ubuntu drivers support your RAID configuration. So there is not really an advantage to use Wubi(uefi) as workaround for RAID issues.

> could I just copy installation.iso into root.disk and delete it after installation?

The root.disk and the installation.iso are on the same Windows partition/drive. If initramfs doesn't find the installation.iso, probably it doesn't find a root.disk, too.

So it is not really a workaround for your issue.

> Or should I need RAID driver/something else?
 
In a lot of cases, boot options are a possible workaround. As a standard Ubuntu install does, Wubiuefi provides that possibility.

To do so, press "ESC" if the following message appears:

```
Completing the Ubuntu installation."
For more installation boot options, press `ESC' now...

```

After that an option menu appears.

You can change the highlighted entry with the arrow keys and change the boot options by pressing `e`. e.g. If you use the entry `Intel graphics workarounds` replace `i915.modeset=0` with your boot option. 

You see the same boot option twice. The first one is for the installer, the second one is for the installed system. see [before--after](https://help.ubuntu.com/community/BootOptions/before--after)

For your issue, maybe boot option `pcie_aspm=off` like [here](http://askubuntu.com/a/706107) is a solution.

If you press `F10` you can use the changed menu entry.

**Comment by clarencechien** [comment]
Try with pcie_aspm=off and TPM off, but it still doesn't work.
Somehow something is blocking the installation to read disk (etc. security feature).
Maybe the dual partition is the only way to go.

**Comment by clarencechien** [comment]
Follow steps from : 
http://ewen.mcneill.gen.nz/blog/entry/2016-12-18-dell-xps-9360-dual-boot/
http://triplescomputers.com/blog/uncategorized/solution-switch-windows-10-from-raidide-to-ahci-operation/
Turn off secure boot, switch RAID to ACHI, problem solved :)

**Comment by hakuna-m** [comment]
Thanks for sharing your solution.

I think that we can close the issue because it is solved. Because Ubuntu with Wubi(uefi) uses the same drivers as Ubuntu without Wubi(uefi), the solution works for both.
