### ISSUE TITLE
wubi getting stuck at creating the virtual disks stage.

### ISSUE THREAD

**Issue by Ronaldo433** [hakuna-m/wubiuefi#58]
the title is self explanatory. the version i am using is wubi16042r319. i am installing it on a newly formatted drive and till now have tried to check for errors using chkdsk and defragmented the drive. but to no avail,still it is getting stuck at the mentioned stage, i have tried to reinstall multiple times.  

a quick reply would be appreciative because i am not able to sleep without it. XD

**Comment by hakuna-m** [comment]
The full error message should be in a log within Windows temp folder. The path name is `%temp%` or something like `C:\Users\YourWindowsName\AppData\Local\Temp`. The name of the log is `wubi-16.04.2-rev319.log` for wubi16042r319.exe.

In the past, I got an error at creating the virtual disks stage if there was not enough space for selected disk size.

**Comment by Ronaldo433** [comment]
the log file is about 2.31 gb large! how the hell am i going to upload that on my shit internet. OMG!

**Comment by Ronaldo433** [comment]
hakuna i tried to install with a smaller disk size and it worked. but i still wonder why it was not installing before even though the drive had more than sufficient space. i am really sorry if i troubled you. thank you for helping me

**Comment by hakuna-m** [comment]
> but i still wonder why it was not installing before even though the drive had more than sufficient space.

Wubiuefi uses the selected installation size only for Wubi disks but needs additional space for the iso file and program files. Wubiuefi subtracts the max iso size from available space. But if the max iso size is too small, the calculation of available space for Wubi disks is wrong.

A second problem of the calculation is that Windows can also use additional space during runtime of Wubiuefi.

> the log file is about 2.31 gb large!

The log file contains all installations with the associated version. At the bottom of the log there should be the most interesting information.
