### ISSUE TITLE
error wubi1604r305.exe

### ISSUE THREAD

**Issue by thamermousa** [hakuna-m/wubiuefi#6]
Ubuntu 12.04.5 LTS (Precise Pangolin) this is good 

![1](https://cloud.githubusercontent.com/assets/3912594/14658582/8e71cfc2-069d-11e6-85c9-816cda622cac.jpg)

Ubuntu 16.04 LTS "Xenial Xerus" This is an error wubi1604r305.exe

![2](https://cloud.githubusercontent.com/assets/3912594/14658861/c6610040-069f-11e6-89ef-0a690fa1cb75.jpg)

wubi-16.04-rev300.log
(((((((((((((((((((
04-19 22:54 DEBUG  TaskList: ### Finished check_iso
04-19 22:54 DEBUG  CommonBackend: Could not find any ISO or CD, downloading one now
04-19 22:54 DEBUG  TaskList: New task download
04-19 22:54 DEBUG  TaskList: ### Running download...
04-19 22:54 DEBUG  btdownloader: downloading http://cdimage.ubuntu.com/daily-live/current/xenial-desktop-amd64.iso.torrent > C:\ubuntu\install\xenial-desktop-amd64.iso
04-19 22:54 ERROR  TaskList: problem getting response info - HTTP Error 404: Not Found
Traceback (most recent call last):
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\common\btdownloader.py", line 78, in download
  File "\lib\bittorrent\download.py", line 129, in download
  File "\lib\wubi\backends\common\btdownloader.py", line 69, in error_callback
DownloadError: problem getting response info - HTTP Error 404: Not Found
04-19 22:54 ERROR  TaskList: Non fatal error problem getting response info - HTTP Error 404: Not Found in task download
04-19 22:54 DEBUG  TaskList: ### Finished download
04-19 22:54 DEBUG  TaskList: New task download
04-19 22:54 DEBUG  TaskList: ### Running download...
04-19 22:54 DEBUG  downloader: downloading http://cdimage.ubuntu.com/daily-live/current/xenial-desktop-amd64.iso > C:\ubuntu\install\xenial-desktop-amd64.iso
04-19 22:54 DEBUG  downloader: Download start filename=C:\ubuntu\install\xenial-desktop-amd64.iso, url=http://cdimage.ubuntu.com/daily-live/current/xenial-desktop-amd64.iso, basename=xenial-desktop-amd64.iso, length=1474953216, text=None
04-19 23:20 DEBUG  TaskList: ### Finished download
04-19 23:20 DEBUG  downloader: download finished (read 1474953216 bytes)
04-19 23:20 DEBUG  TaskList: New task check_iso
04-19 23:20 DEBUG  TaskList: ### Running check_iso...
04-19 23:20 DEBUG  CommonBackend: Checking C:\ubuntu\install\xenial-desktop-amd64.iso
04-19 23:20 DEBUG  Distro:   checking Ubuntu ISO C:\ubuntu\install\xenial-desktop-amd64.iso
04-19 23:20 DEBUG  WindowsBackend:   extracting .disk\info from C:\ubuntu\install\xenial-desktop-amd64.iso
04-19 23:20 DEBUG  Distro:   parsing info from str=Ubuntu 16.04 LTS "Xenial Xerus" - Release amd64 (20160417.1)
04-19 23:20 DEBUG  Distro:   parsed info={'name': 'Ubuntu', 'subversion': 'Release', 'version': '16.04', 'build': '20160417.1', 'codename': 'Xenial Xerus', 'arch': 'amd64'}
04-19 23:20 INFO   Distro: Found a valid iso for Ubuntu: C:\ubuntu\install\xenial-desktop-amd64.iso
04-19 23:20 DEBUG  TaskList: New task get_file_md5
04-19 23:20 DEBUG  TaskList: #### Running get_file_md5...
04-19 23:21 DEBUG  TaskList: #### Finished get_file_md5
04-19 23:21 ERROR  CommonBackend: Invalid md5 for ISO C:\ubuntu\install\xenial-desktop-amd64.iso (d2c082c976f35605a1e53e067c5e69d4 != 014d6dcdcc9c694158601c1cd1577c6b)
None
04-19 23:21 DEBUG  TaskList: ### Finished check_iso
04-19 23:21 ERROR  TaskList: Could not retrieve the required installation files
Traceback (most recent call last):
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\common\backend.py", line 600, in get_iso
Exception: Could not retrieve the required installation files
04-19 23:21 DEBUG  TaskList: # Cancelling tasklist
04-19 23:21 ERROR  root: Could not retrieve the required installation files
Traceback (most recent call last):
  File "\lib\wubi\application.py", line 58, in run
  File "\lib\wubi\application.py", line 132, in select_task
  File "\lib\wubi\application.py", line 158, in run_installer
  File "\lib\wubi\backends\common\tasklist.py", line 197, in __call__
  File "\lib\wubi\backends\common\backend.py", line 600, in get_iso
Exception: Could not retrieve the required installation files
04-19 23:21 DEBUG  TaskList: # Finished tasklist
)))))))))))))))))))))))))

**Comment by nhymxu** [comment]
seam like md5 store in wubi not same with your iso ( or download process is broken iso )
Wait few hours for ubuntu release 16.04

**Comment by hakuna-m** [comment]
**d2c082c976f35605a1e53e067c5e69d4** and **014d6dcdcc9c694158601c1cd1577c6b** are both valid md5 checksums of **xenial-desktop-amd64.iso** but checksums of different days.

Currently, we use daily build isos as older official Wubi versions also did. Unfortunately,  "daily build" means that the checksums change from day to day and additionally, different sources of information are not always updated at same time.       

IMHO we should use beta versions instead of daily builds to provide more stable downloads. But for 16.04, it makes no sense. In few hours, Wubi will use automatically the stable downloads of the final release.   

BTW wubi-16.04-rev**300**.log is not the log file of wubi1604r**305**.exe

**Comment by hakuna-m** [comment]
If you need a solution as soon as possible: Download [xenial-desktop-amd64.iso](http://cdimage.ubuntu.com/daily-live/current/xenial-desktop-amd64.iso xenial-desktop-amd64.iso) and [wubi1604r305.exe](https://github.com/hakuna-m/wubiuefi/releases/download/1604r305/wubi1604r305.exe) and copy both files in the same folder. Run **wubi1604r305.exe** but disconnect internet during Windows part of installation.

**Comment by thamermousa** [comment]
**thank you
**
**wubi1510-32.exe This is an excellent tests

How the amendment and work like this**

![dfdf](https://cloud.githubusercontent.com/assets/3912594/14718118/67ebecfa-07fd-11e6-92bd-af8e13183ab3.jpg)


**menu.lst Thus Excellent**
-------------------------------------
title Ubuntu 15.10 (Wily Werewolf) From USB HDD ( 7 G.B ) \n Ubuntu Arabic ( 7 G.B ) From On Root.disk Swap.disk
find --set-root /wubildr
chainloader /wubildr.mbr

![dfdsf](https://cloud.githubusercontent.com/assets/3912594/14718180/c0eba37c-07fd-11e6-8a4d-d4b25ae34dee.jpg)

**We will wait for you to file ... thank you
**

**Comment by thamermousa** [comment]
**These things are implemented, a good**
> If you need a solution as soon as possible: Download xenial-desktop-amd64.iso and wubi1604r305.exe and copy both files in the same folder. Run wubi1604r305.exe but disconnect internet during Windows part of installation.

**Comment by hakuna-m** [comment]
> **wubi1510-32.exe This is an excellent tests**

Some months ago, I built [wubi1510-32.exe](https://www.dropbox.com/sh/6uqomp8l1frcd1y/AACfiwyZGIPZgJCr5tpL49dra/wubi1510-32.exe?dl=0) for some devices with a [32 bit UEFI](https://github.com/hakuna-m/wubiuefi/wiki#uefi32). Meanwhile it should be not necessary to use a special version for a 32 bit UEFI, because the current versions include this feature. In your case, I don't understand why you used wubi1510-32.exe. If you have a non-UEFI installation of Windows, the changes for a 32 bit UEFI are unused. Non-UEFI computers use **wubildr.mbr** and **wubildr** to boot Ubuntu.

Non-UEFI computers boots from Windows menu into **wubildr.mbr** and **wubildr.mbr** loads **wubildr**.  An additional **menu.lst** or bootloader is not needed. The configuration file of wubildr is **grub.cfg** because wubildr contains GRUB2. **menu.lst** is the configuration file of a previous version of GRUB. 

Probably, I don't understand your swap.disk question. The default size of swap.disk is 256 MiB (268435456 bytes) but you can increase this size.

**Comment by thamermousa** [comment]
> Some months ago, I built wubi1510-32.exe for some devices with a 32 bit UEFI. Meanwhile it should be not necessary to use a special version for a 32 bit UEFI, because the current versions include this feature. In your case, I don't understand why you used wubi1510-32.exe. If you have a non-UEFI installation of Windows, the changes for a 32 bit UEFI are unused. Non-UEFI computers use wubildr.mbr and wubildr to boot Ubuntu.

**Because this method to save the changes**
**And not cd-dvd - live ubuntu**

![123](https://cloud.githubusercontent.com/assets/3912594/14729465/cda548f4-0846-11e6-92c1-575c72dcd29f.png)

![14](https://cloud.githubusercontent.com/assets/3912594/14729473/e07344c2-0846-11e6-895a-53b7d1ba6d81.png)


> Non-UEFI computers boots from Windows menu into wubildr.mbr and wubildr.mbr loads wubildr. An additional menu.lst or bootloader is not needed. The configuration file of wubildr is grub.cfg because wubildr contains GRUB2. menu.lst is the configuration file of a previous version of GRUB.

**you are right**

 But I have no experience with this file grub.cfg

This is an excellent and stable
![145514](https://cloud.githubusercontent.com/assets/3912594/14729527/5a39e716-0847-11e6-8186-6eb96486fe74.jpeg)

not good
![1515](https://cloud.githubusercontent.com/assets/3912594/14729541/741d28dc-0847-11e6-9a68-01ef8bf062df.jpeg)

**Comment by thamermousa** [comment]
> Probably, I don't understand your swap.disk question. The default size of swap.disk is 256 MiB (268435456 bytes) but you can increase this size.

The default size of swap.disk is 256 MiB , But I want him bigger than this

**I found the explanation here :**
https://www.howtoforge.com/ubuntu-swap-file

256MB OR 1024MB on USB
4096MB on HDD

swap.disk Whenever equal size ram Be good

-----------------------------------------------------

**See also my boot image on USB Or HDD**

![555](https://cloud.githubusercontent.com/assets/3912594/14730138/9b20671e-084c-11e6-8359-d62b4eaeccfb.jpg)

![556](https://cloud.githubusercontent.com/assets/3912594/14730146/a87ba086-084c-11e6-8579-0740f71fb5c9.jpg)

![557](https://cloud.githubusercontent.com/assets/3912594/14730149/afd63bca-084c-11e6-8a80-2c805fc0fa9b.jpg)

**Comment by thamermousa** [comment]
**I forgot to tell you**

**UEFI I do not use it**

![4647](https://cloud.githubusercontent.com/assets/3912594/14731093/d7079c80-0855-11e6-8ebe-358083b669be.jpg)


![5757](https://cloud.githubusercontent.com/assets/3912594/14731101/df74f610-0855-11e6-8c1b-1a85831445a5.jpg)


**This easy and simple**
![4777](https://cloud.githubusercontent.com/assets/3912594/14731149/65d04dd6-0856-11e6-82c2-c8abc6082cd5.jpg)

**Comment by hakuna-m** [comment]
> The default size of swap.disk is 256 MiB , But I want him bigger than this

see [How do I increase my swap space](https://wiki.ubuntu.com/WubiGuide#How_do_I_increase_my_swap_space.3F)

> Because this method to save the changes
> And not cd-dvd - live ubuntu

Do you want to get all your live systems writeable ? Maybe, you want a live system in persistent mode. see [here](https://wiki.ubuntu.com/LiveUsbPendrivePersistent)

Wubi does an installation on virtual partitions (=files root.disk, swap.disk), it doesn't create a live system in persistent mode. It needs iso files with a special content. But, if you need GRUB2, you can use installed GRUB2 on root.disk. 

If you need help in Arabian, see [here](http://ubuntuforums.org/forumdisplay.php?f=264).

**Comment by thamermousa** [comment]
**Thank you hakuna-m
**** I benefited a lot from you **

But the Arabic-language is very much subsidized - The old threads

> Do you want to get all your live systems writeable ? Maybe, you want a live system in persistent mode. see here

I will try to expand and Increase the size root.disk

Because I got a lot of software version

It is an excellent but small in size

I want her for your hdd not for usb

**Comment by hakuna-m** [comment]
> The old threads

You are right. Theoretically, every language has its own support but in fact, these Arabic threads are old.

> I will try to expand and Increase the size root.disk

see [Resize and Duplicate Wubi Disk](https://help.ubuntu.com/community/ResizeandDuplicateWubiDisk) or [Resize Wubi Disk](https://help.ubuntu.com/community/ResizeWubiDisk)

> I want her for your hdd not for usb

The method should work for non-USB-HDD, too. But of course, if you just want to increase your root.disk, it is not what you want.

If you need more space for non system files (e.g. video files), you can save these files within **/host**.** /host** is the Windows drive with Ubuntu.

**Comment by thamermousa** [comment]
I apologize for being late
Cleaned half the room for creeping Gecko 
and The electricity went out for PC

-------------------

> If you need more space for non system files (e.g. video files), you can save these files within /host.** /host** is the Windows drive with Ubuntu.

**That's what I want to do, of course /host/ubuntu/disks**

![2016-04-25 00-34-52](https://cloud.githubusercontent.com/assets/3912594/14770627/62593742-0a7e-11e6-9994-e697774af489.png)

But I do not want you so home.disk

I want, as in the picture

![2016-04-25 00-48-14](https://cloud.githubusercontent.com/assets/3912594/14770662/ae727de0-0a7f-11e6-873a-9ba9f4fea0f9.png)

/host/ubuntu/disks/home/th
Is this how possible

home.disk , Its currency, but I did not like his class

usr.disk It gives me an error 

> see Resize and Duplicate Wubi Disk or Resize Wubi Disk

**He applied and was excellent**

**Comment by thamermousa** [comment]
By the way , This file to work usr.disk The error orders 
https://wiki.ubuntu.com/WubiGuide#How_do_I_resize_the_virtual_disks.3F

 [This file](https://wiki.ubuntu.com/WubiGuide?action=AttachFile&do=view&target=wubi-add-virtual-disk
) 

But this thing work with me without problems , It is an excellent
> home.disk 
> sudo sh wubi-add-virtual-disk /home 15000

But better to folder /home  are completely separated , As in the previous picture

But now this file is the best expansion root.disk

Thank you

**Comment by hakuna-m** [comment]
> /host/ubuntu/disks/home/th
> Is this how possible
If you create a folder **home** within  **/host/ubuntu/disks** and a folder **th** within the new folder **home**, it is possible, of course. It is also possible to create this folders with Windows. In your case, the Windows path should be **E:\ubuntu\disks** instead of **/host/ubuntu/disks**. But feel free to use the folder of your choice. It is not necessary to use a folder within **/host/ubuntu/disks**  with a special name. e.g. if you use **/host/videos**, it would be also a valid choice.

**Comment by thamermousa** [comment]
**I did not understand you**
**How to be the default for all in this folder**

![2016-04-25 22-32-45](https://cloud.githubusercontent.com/assets/3912594/14796557/a5b2cb58-0b36-11e6-87f6-e99a3a3a7c88.png)

**Comment by hakuna-m** [comment]
**/home/th** also includes system files. So it is not possible to move **all** files to a Windows file system, but the largest files are often non-system files (e.g. video files, pictures, ...). So you can move video files, pictures, audio files, ... to a folder of the Windows file system.

**Comment by thamermousa** [comment]
Yes you are right ...

Plasma-Desktop I got this interface And where the options put downloads, images and video files

But I did not like the interface , And delete Plasma-Desktop

Thank you ... I had the pleasure to help you
