### ISSUE TITLE
Use my Ubuntu webui installation with a new windows

### ISSUE THREAD

**Issue by gonzela2006** [hakuna-m/wubiuefi#70]
Hello,

Can I use my existing Ubuntu webui installation with a newly installed windows?if yes, how can I do this?

Thanks

**Comment by hakuna-m** [comment]
> Can I use my existing Ubuntu webui installation with a newly installed windows?

Yes, it is possible to copy an existing Wubi installation to a newly installed Windows. 
> if yes, how can I do this?

IMHO, the easiest way is to install Ubuntu with Wubiuefi on the newly installed Windows and then copy a backup of your old Wubi install to the new installation.
 
 * The old Wubi install is within folder **ubuntu**.
 * If Wubiuefi installs Ubuntu, it overwrites root folder/directory **ubuntu** on installation drive and it detects root folders/directories **ubuntu** on any drive. So before you install Ubuntu with Wubiuefi, rename all root folders/directories **ubuntu** to e.g. **ubuntuold** on connected drives.
 * It is only necessary to run Windows part of installation, Windows part of installation ends with  
![](https://raw.githubusercontent.com/wiki/hakuna-m/wubiuefi/images/Install-Restart.png) 
 * After Windows part of installation, you can replace **ubuntu** with your backup of this folder.
 * If the Windows drive has changed, there is an error message about a missing file **/host/ubuntu/disks/root.disk** and it boots into busybox.
 * You can correct this at busybox prompt. Type 
`blkid`
to get a list of possible devices. IMHO, a known label name and the type **ntfs** should indicate which is your Windows drive with Ubuntu. Type  
`mount -t ntfs /dev/sdxn /host`
to mount your Windows drive/partition with Ubuntu. Replace **/dev/sdxn** with the name of your device. Type
`exit`    
to try it again.
 * To permanently update the changed drive, type
`sudo update-grub`
on Ubuntu.

**Comment by gonzela2006** [comment]
Thank you very much :) I'll try it and feed you back

**Comment by gonzela2006** [comment]
@hakuna-m I can't mount the drive where I installed Ubuntu as you can see in the below images

![22219574_10155163681254217_79687961_o](https://user-images.githubusercontent.com/3768012/31059450-a629dfe0-a702-11e7-9037-7bec1adce9f0.jpg)
![22164060_10155163681309217_1481005804_o](https://user-images.githubusercontent.com/3768012/31059449-a6262954-a702-11e7-83f7-daed7070b11b.jpg)

**Comment by hakuna-m** [comment]
In your case, it is easier to edit GRUB menu entry. 

If needed, you can type
`reboot`
from initramfs prompt to reboot.

If GRUB menu appears, type <kbd>e</kbd> to edit the first Ubuntu menu entry.

Replace in the line beginning with **linux** 
`root=UUID=01CEDFE37DB66A00`
with
`root=/dev/sda5`

then press <kbd>F10</kbd> to boot

**Comment by gonzela2006** [comment]
Should I run sudo update-grub after booting to ubuntu

**Comment by gonzela2006** [comment]
Thank you very much :) It is working well :+1: 
The last question please, changing brightness has no effect, when I increase or decrease it, it is still the same

**Comment by hakuna-m** [comment]
Your last question is a general Ubuntu question which does not depend on Wubi(uefi).

Answers are e.g. at [askubuntu](https://askubuntu.com/questions/762764/cant-change-brightness-in-ubuntu-16-04-lts).

**Comment by gonzela2006** [comment]
Thanks for your time and support :)
