### ISSUE TITLE
Pop!_OS support

### ISSUE THREAD

**Issue by markhaehnel** [hakuna-m/wubiuefi#83]
Do you consider adding support for System76's Pop!_OS? It's based on Ubuntu and uses Ubiquity so this shouldn't be a problem.

**Comment by hakuna-m** [comment]
Did you test the existing [various distros/versions](https://github.com/hakuna-m/wubiuefi/wiki#various-distrosversions) feature ?

As far as I can see, the necessary files for desktop environment "Wubi gz" are available on ISO.

**Comment by markhaehnel** [comment]
Didn't even know that this feature is available. Will report back if it works.

**Comment by cata0309** [comment]
Anybody here ?

**Comment by cata0309** [comment]
Can anybody give me some instructions ?

**Comment by markhaehnel** [comment]
The "various distros/versions" feature just works. No problems at all.

**Comment by cata0309** [comment]
Well how did you do it ???

**Comment by markhaehnel** [comment]
https://github.com/hakuna-m/wubiuefi/wiki#various-distrosversions

**Comment by rfdomingues98** [comment]
What versions did you use? I tried the Pop!_OS 18.04 iso with Wubiuefi 18041r333 with Wubi Gz and it gave me an error "Cannot download the metalink and therefore the ISO"... I had the pop!_os iso in the same folder as the wubi exe (folder had only these 2 files)

**Comment by cata0309** [comment]
Rename the iso to the original one, ubuntu and so on, the default one

dum., 10 feb. 2019, 01:18 Ricardo Domingues <notifications@github.com> a
scris:

**Comment by rfdomingues98** [comment]
If i try to rename the Pop!_OS to the default Ubuntu iso and choose 'Ubuntu distro' on the Wubiuefi, it starts downloading the ubuntu iso torrent, if i do it with Wubi gz i still get the same error...

**Comment by cata0309** [comment]
Do it with the normal wubi, and search on youtube, it was a video about
Linux Mint.
I forgot about the dual boot idea, I am now a linux user.

dum., 10 feb. 2019, 01:25 Ricardo Domingues <notifications@github.com> a
scris:

**Comment by hakuna-m** [comment]
The full name of the iso does not matter. Wubiuefi detects files with suffix .iso as iso. But it is necessary that the iso contains all files which are defined for selected environment. If all necessary files are available the environment is preselected.

So if you have to select a desktop environment there is something wrong.

So do not rename ISOs or select manually a desktop environment. There is a [log](https://github.com/hakuna-m/wubiuefi/wiki/FAQ#where-are-the-logs-for-wubiuefi-) with the reason of the issue.

e.g.
```
DEBUG  Distro:   checking Wubi gz ISO pop_os.iso
DEBUG  Distro:     does not contain casper\vmlinuz
```
means Pop_os.iso does not cotain **casper\vmlinuz** for environment Wubi gz

If Pop_os.iso still needs **casper\vmlinuz.efi** of older Ubuntu versions, try an older Wubiuefi version e.g. [1804r330](https://github.com/hakuna-m/wubiuefi/releases/tag/1804r330) with **casper\vmlinuz.efi** configuration.
