### ISSUE TITLE
WUBI 14.04.4 won't run on Windows 7

### ISSUE THREAD

**Issue by gomoku** [hakuna-m/wubiuefi#9]
Hello,

I have Windows 7 SP1 64 Ultimate UEFI:
Wersja 6.1.7601 Service Pack 1 Kompilacja 7601

I downloaded Xubuntu 14.04.4 ISO from:
http://cdimage.ubuntu.com/xubuntu/releases/14.04/release/xubuntu-14.04.4-desktop-amd64.iso

then downloaded Wubi for Ubuntu 14.04.4 (rev.304) from:
https://github.com/hakuna-m/wubiuefi/releases/tag/14044r304 (wubi14044r306.exe)

Both the ISO and WUBI are placed in the same folder.

When run WUBI binary...nothing happens - it even won't run, nothing shows up on the screen (even when run as administrator), just circle of cursor is rotating for a few seconds and then dissappears. 

I remember a few month ago, on my old computer with Windows XP SP3 32 Pro, I successfully installed Xubuntu / Ubuntu / Lubuntu 14.04 in WIndows XP using WUBI, now after I switched to a new PC & OS, WUBI won't even run.

[Edited]
OK. I workarounded the issue after asking uncle Google for a phrase "wubi wont run" - I found someone's answer saying something about checking WUBI log files in some Windows TEMP folder (I didn't even know that WUBI creates the log file), so the log says WUBI was scanning & checking all my PC's partitions for any ISO files and failed on some ISO file with

> Error: D:\x.iso: Can not open file as archive

After I changed extension name "iso" to "ixo" (thereby making WUBI skip this file), WUBI finally runs.

I wonder why WUBI scans all my partiitons for all ISOS, instead of just simply loading the proper ISO file located in the same folder...

The second thing is , even omitting the above, why does it fail on some bad ISO, instead of just skipping the bad ISO?

**Comment by hakuna-m** [comment]
> I wonder why WUBI scans all my partiitons for all ISOS, instead of just simply loading the proper ISO file located in the same folder...

As far as I know (I don't have additional information from the first developers), the first scans should pre-select a desktop enviroment, if local CDs (meanwhile DVDs) or USB drives like USB keys are available which contain a valid Ubuntu image in the root folder. 

> The second thing is , even omitting the above, why does it fail on some bad ISO, instead of just skipping the bad ISO?

IMHO, it is only a question of error handling. It is always possible to skip errors.

**Comment by hakuna-m** [comment]
I prepared a patch for the next release which worked in my test:
```
--- a/src/wubi/backends/common/distro.py
+++ b/src/wubi/backends/common/distro.py
@@ -110,6 +110,9 @@ class Distro(object):
             log.debug('    file does not exist')
             return False
         files = self.backend.get_iso_file_names(iso_path)
+        if not files:
+            log.debug('    does not contain any file')
+            return False
         files = [f.strip().lower() for f in files]
         required_files = self.get_required_files()
         for file in required_files:

```
If there is a mismatched iso, it skips the iso with:
```
05-22 16:28 DEBUG  Distro:   checking Ubuntu ISO Z:\bad.iso
05-22 16:28 DEBUG  Distro:     does not contain any file
```

**Comment by hakuna-m** [comment]
I added also a preselection of dektop environment for local ISOs. The search path for local ISOs is:
* pre-defined ISOs with parameter **isopath** e.g.

`wubi1604r308.exe --isopath=ubuntu-16.04-desktop-amd64.iso`
* same folder as wubi.exe
* root folder of Windows drives
* Windows desktop

BTW: There is only a preselection for local DVDs where you run wubi.exe from. Maybe, that behaviour is not up to date and a change is a wish for the next release......
