### ISSUE TITLE
Ubuntu 18.04 grub issue

### ISSUE THREAD

**Issue by hakuna-m** [hakuna-m/wubiuefi#91]
Currently, we test Wubiuefi for Ubuntu 18.04 final beta.

The installation of grub did not work.

But IMHO, we found the reason. Because of new snap packages there were a lot of existing loop devices when the installer created loop devices for the Wubi disks.

So **root.disk** is /dev/loop**10** which is a problem for grub. The range of supported loop devices is from /dev/loop**0** to /dev/loop**9**.

Either it is necessary to change the selection `/dev/loop[0-9]` in 

**/etc/grub.d/10_linux** from package **grub-common** (maybe also other files which are not needed for Wubiuefi) 
**/etc/grub.d/10_lupin** from package **lupin-support**
**/usr/share/lupin-support/grub-mkimage** from package **lupin-support**

or to create loop devices for Wubi disks before loop devices for snaps exist.

**Comment by hakuna-m** [comment]
There is an [Ubuntu bug report](https://bugs.launchpad.net/ubuntu/+source/grub-installer/+bug/1762034)

Maybe, the bug report results in some changes of the official Ubuntu packages. But meantime I'll try to create a fix with a workaround for Wubiuefi.

The fix should do something like that.

1. Create a dummy loop device before snap creates its loop devices (TBD)
2. The installer detach the dummy loop device and create its own loop device with the name of the dummy loop device (e.g. /dev/loop2). (TBD)
3. The installation works with /dev/loop2
4. The installed system has no problem because the first Wubi disk is always /dev/loop0.

**Comment by hakuna-m** [comment]
The issue has been fixed with the workaround which I described above. The source code has been released. After some internal tests we will release an exe file, too.

**Comment by hakuna-m** [comment]
The internal tests were successful. So I added the exe file to [Wubi for Ubuntu 18.04 (rev 330)](https://github.com/hakuna-m/wubiuefi/releases/tag/1804r330).

**Comment by ilianiron** [comment]
This wubi work only for ubuntu-gnome! Test ubuntu mate, Kubuntu, Budgie with latest daily iso-not work. 15-20 sec when began installing, computer restarts!

**Comment by hakuna-m** [comment]
>  Test ubuntu mate, Kubuntu, Budgie with latest daily iso-not work. 15-20 sec when began installing, computer restarts!

We can confirm your issue. Currently, we try to debug it. As far as I know there were also similar issues with releases under development in the past.
