### ISSUE TITLE
Kubuntu displays briefly for a moment then restarts PC

### ISSUE THREAD

**Issue by NotShige** [hakuna-m/wubiuefi#92]
So I finally got the hang to use WUBI, installed Ubuntu, removed it, and decided to try Kubuntu. But, the desktop would only show up for a second then my laptop suddenly restarts. 

It's not like #81 where it would say that the installer crashed, it just restarts immediately.

**Comment by hakuna-m** [comment]
It looks like a known issue of Kubuntu. see notes of our [releases](https://github.com/hakuna-m/wubiuefi/releases/latest):

> (*) Note: Kubuntu needs a workaround ( #10 )

**Comment by NotShige** [comment]
That did the trick! Thanks!
